import { deepFreeze } from '../builders';
import { ALL_HERO_CLASSES, defineArmor } from './types';

export const CHRONICLE1_ARMOR = deepFreeze([
  defineArmor({ id: 'armor-greywatch-guard-coat', name: 'Greywatch Guard Coat', description: 'A blue-grey watch coat with hidden mail at the collar and room to move through narrow streets.', allowedClasses: ['warrior', 'warden'], stats: { armor: 2, health: 4 }, value: 18, tags: ['coat', 'greywatch'], tier: 1, gates: { minChapter: 1 } }),
  defineArmor({ id: 'armor-caravan-leathers', name: 'Caravan Leathers', description: 'Layered road leathers repaired at every buckle so a driver can work, ride, and fight in them.', allowedClasses: ['warrior', 'warden'], stats: { armor: 1, health: 6 }, value: 16, tags: ['leather', 'caravan'], tier: 1, gates: { minChapter: 1 } }),
  defineArmor({ id: 'armor-scout-halfmail', name: 'Scout Halfmail', description: 'A cropped mail shirt that protects the ribs without announcing every step through wet brush.', allowedClasses: ['warden'], stats: { armor: 3, focus: 2 }, value: 24, tags: ['mail', 'scout'], tier: 1, gates: { minChapter: 1 } }),
  defineArmor({ id: 'armor-black-banner-cuirass', name: 'Black Banner Cuirass', description: 'A captured infantry breastplate scrubbed clean of tar while retaining its dependable rivets.', allowedClasses: ['warrior'], stats: { armor: 5 }, value: 48, tags: ['plate', 'black-banner'], tier: 2, gates: { minChapter: 2 } }),
  defineArmor({ id: 'armor-redwater-scale', name: 'Redwater Scale Coat', description: 'River-town scales sewn over flexible hide to turn arrows without becoming dead weight in water.', allowedClasses: ['warrior', 'warden'], stats: { armor: 4, ward: 1 }, value: 50, tags: ['scale', 'redwater'], tier: 2, gates: { minChapter: 3 } }),
  defineArmor({ id: 'armor-orc-peace-lamellar', name: 'Free Host Peace Lamellar', description: 'Horn and iron plates tied with white cord, worn by orc envoys who still expect an ambush.', allowedClasses: ['warrior', 'warden'], stats: { armor: 4, ward: 2 }, value: 56, tags: ['lamellar', 'orc', 'peace'], tier: 2, gates: { minChapter: 4, minReputation: 8 } }),
  defineArmor({ id: 'armor-flooded-chain', name: 'Flooded Chain Shirt', description: 'Oiled fine-link mail shortened above the knee so its wearer can cross channels without sinking.', allowedClasses: ['warrior', 'warden'], stats: { armor: 4, health: 6 }, value: 46, tags: ['mail', 'drowned-road'], tier: 2, gates: { minChapter: 3 } }),
  defineArmor({ id: 'armor-ferryman-oilskin', name: 'Ferryman Oilskin', description: 'A reed-lined oilskin that sheds cold rain and hides a few thin plates over the vital organs.', allowedClasses: ['mage', 'warden'], stats: { armor: 2, ward: 3, focus: 3 }, value: 38, tags: ['oilskin', 'river'], tier: 2, gates: { minChapter: 3 } }),
  defineArmor({ id: 'armor-embervault-apron', name: 'Embervault Foreman Apron', description: 'A heavy leather apron with copper plates protecting the chest from sparks, tools, and knives.', allowedClasses: ['warrior', 'warden'], stats: { armor: 5, health: 8 }, value: 68, tags: ['leather', 'embervault'], tier: 3, gates: { minChapter: 5 } }),
  defineArmor({ id: 'armor-cinderplate', name: 'Cinderplate Harness', description: 'Heat-tempered plates joined with dark leather that remains flexible beside an open furnace.', allowedClasses: ['warrior'], stats: { armor: 7, health: 6 }, value: 90, tags: ['plate', 'fire'], tier: 3, gates: { minChapter: 5 } }),
  defineArmor({ id: 'armor-conclave-sealcoat', name: 'Conclave Sealcoat', description: 'A fitted pale coat embroidered with measured ward lines rather than ceremonial decoration.', allowedClasses: ['mage'], stats: { armor: 2, ward: 6, focus: 5 }, value: 82, tags: ['cloth', 'conclave', 'seal'], tier: 3, gates: { minChapter: 5, minReputation: 8 } }),
  defineArmor({ id: 'armor-abbey-field-vestment', name: 'Abbey Field Vestment', description: 'A mail-backed vestment built for roadside ministry where prayers may end under arrow fire.', allowedClasses: ['mage', 'warrior'], stats: { armor: 4, ward: 4, health: 7 }, value: 88, tags: ['mail', 'abbey'], tier: 3, gates: { minChapter: 5 } }),
  defineArmor({ id: 'armor-crownless-sentinel-mail', name: 'Crownless Sentinel Mail', description: 'Dense keep mail reinforced at the shoulders for holding stair turns against heavier weapons.', allowedClasses: ['warrior'], stats: { armor: 9, ward: 3, health: 10 }, value: 190, tags: ['mail', 'crownless'], tier: 5, gates: { minChapter: 8 } }),
  defineArmor({ id: 'armor-voss-command-plate', name: 'Voss Command Plate', description: 'A black command harness engineered to survive a broken line long enough to issue new orders.', allowedClasses: ['warrior'], stats: { armor: 10, ward: 2, health: 8 }, value: 220, tags: ['plate', 'voss'], tier: 5, gates: { minChapter: 8, questId: 'ch08-main-voss-offers-order' } }),
  defineArmor({ id: 'armor-goblin-patchcloak', name: 'Goblin Patchcloak', description: 'Dozens of waterproof scraps form a quiet cloak with pockets placed by people who use them.', allowedClasses: ['mage', 'warden'], stats: { armor: 2, ward: 2, focus: 4 }, value: 40, tags: ['cloak', 'goblin'], tier: 2, gates: { minChapter: 3 } }),
  defineArmor({ id: 'armor-stonehand-harness', name: 'Stonehand Harness', description: 'Rukhar’s spare lamellar is weighted forward for protecting another fighter in a shield line.', allowedClasses: ['warrior'], stats: { armor: 8, ward: 2, health: 10 }, value: 132, tags: ['lamellar', 'orc', 'companion'], tier: 4, gates: { minChapter: 6, questId: 'ch04-companion-the-cost-of-peace' } }),
  defineArmor({ id: 'armor-mara-raincloak', name: 'Mara’s Raincloak', description: 'A scout captain’s raincloak with silent fasteners, map sleeves, and fine mail in the lining.', allowedClasses: ['warden'], stats: { armor: 6, ward: 4, focus: 6 }, value: 120, tags: ['cloak', 'scout', 'companion'], tier: 4, gates: { minChapter: 6, questId: 'ch02-companion-mara-scouts-before-silver' } }),
  defineArmor({ id: 'armor-caldus-healer-mail', name: 'Caldus’s Healer Mail', description: 'Close-set rings protect a field healer without catching on bandages, satchels, or a patient.', allowedClasses: ['warrior', 'mage'], stats: { armor: 7, ward: 5, health: 12 }, value: 148, tags: ['mail', 'healer', 'companion'], tier: 4, gates: { minChapter: 6, questId: 'ch05-companion-caldus-the-first-hostages' } }),
  defineArmor({ id: 'armor-lyra-warded-mantle', name: 'Lyra’s Warded Mantle', description: 'A dark mantle stitched with corrected Conclave formulae that resist force without hiding it.', allowedClasses: ['mage'], stats: { armor: 3, ward: 8, focus: 8 }, value: 150, tags: ['cloth', 'ward', 'companion'], tier: 4, gates: { minChapter: 6, questId: 'ch05-companion-lyra-and-the-embervault-ward' } }),
  defineArmor({ id: 'armor-road-council-coat', name: 'Road Council Coat', description: 'A formal traveling coat reinforced for delegates who must survive the consequences of a vote.', allowedClasses: ALL_HERO_CLASSES, stats: { armor: 7, ward: 6, health: 10 }, value: 210, tags: ['coat', 'council'], tier: 5, gates: { minChapter: 8, minReputation: 25 } }),
]);
