import { deepFreeze } from '../builders';
import { ALL_HERO_CLASSES, defineArtifact } from './types';

/** Story evidence is priceless and therefore never enters the merchant economy. */
export const CHRONICLE1_ARTIFACTS = deepFreeze([
  defineArtifact({
    id: 'quest-voss-sealed-order',
    name: "Voss's Sealed Order",
    description: 'An authenticated field order links Marshal Voss to troop movements hidden from the road councils.',
    allowedClasses: ALL_HERO_CLASSES,
    stats: {},
    value: 0,
    tags: ['quest', 'evidence', 'voss'],
    tier: 3,
    gates: { minChapter: 5 },
  }),
  defineArtifact({
    id: 'quest-greywatch-witness-statement',
    name: 'Greywatch Witness Statement',
    description: 'Several survivors marked this careful account of the first attack before their stories could be altered.',
    allowedClasses: ALL_HERO_CLASSES,
    stats: {},
    value: 0,
    tags: ['quest', 'evidence', 'greywatch'],
    tier: 1,
    gates: { minChapter: 2 },
  }),
  defineArtifact({
    id: 'quest-royal-arrowhead',
    name: 'Royal-Forged Arrowhead',
    description: 'A stamped military arrowhead found at Greywatch contradicts the raiders blamed for the opening attack.',
    allowedClasses: ALL_HERO_CLASSES,
    stats: {},
    value: 0,
    tags: ['quest', 'evidence', 'royal-armory'],
    tier: 1,
    gates: { minChapter: 2 },
  }),
  defineArtifact({
    id: 'quest-redwater-truce-copy',
    name: 'Redwater Truce Copy',
    description: 'The signed river truce records terms accepted by both delegations and exposes anyone who breaks them.',
    allowedClasses: ALL_HERO_CLASSES,
    stats: {},
    value: 0,
    tags: ['quest', 'diplomacy', 'redwater'],
    tier: 3,
    gates: { minChapter: 4 },
  }),
  defineArtifact({
    id: 'quest-embervault-ledger',
    name: 'Embervault Supply Ledger',
    description: 'Coded mine entries trace stolen ore, secret payments, and siege components to the same procurement chain.',
    allowedClasses: ALL_HERO_CLASSES,
    stats: {},
    value: 0,
    tags: ['quest', 'evidence', 'embervault'],
    tier: 3,
    gates: { minChapter: 5 },
  }),
  defineArtifact({
    id: 'quest-hostage-list',
    name: 'Hidden Hostage List',
    description: 'A guard clerk recorded every captive, transfer date, and false release order in a cramped private hand.',
    allowedClasses: ALL_HERO_CLASSES,
    stats: {},
    value: 0,
    tags: ['quest', 'evidence', 'hostages'],
    tier: 4,
    gates: { minChapter: 6 },
  }),
  defineArtifact({
    id: 'quest-crownless-access-seal',
    name: 'Crownless Access Seal',
    description: 'A captured brass seal identifies an authorized route through the keep without proving who issued it.',
    allowedClasses: ALL_HERO_CLASSES,
    stats: {},
    value: 0,
    tags: ['quest', 'access', 'crownless'],
    tier: 4,
    gates: { minChapter: 7 },
  }),
  defineArtifact({
    id: 'quest-patron-cipher-letter',
    name: "Patron's Cipher Letter",
    description: 'A partially decoded letter reveals that the Black Banner campaign answered to a patient foreign patron.',
    allowedClasses: ALL_HERO_CLASSES,
    stats: {},
    value: 0,
    tags: ['quest', 'evidence', 'cipher'],
    tier: 5,
    gates: { minChapter: 8 },
  }),
]);
