import { deepFreeze } from '../builders';
import { ALL_HERO_CLASSES, defineCharm } from './types';

export const CHRONICLE1_CHARMS = deepFreeze([
  defineCharm({ id: 'charm-greywatch-key', name: 'Greywatch Gate Key', description: 'A retired gate key filed smooth at the teeth and carried as a reminder that doors need keepers.', allowedClasses: ALL_HERO_CLASSES, stats: { armor: 1, health: 2 }, value: 18, tags: ['key', 'greywatch'], tier: 1, gates: { minChapter: 1 } }),
  defineCharm({ id: 'charm-medicine-wagon-token', name: 'Medicine Wagon Token', description: 'A stamped brass token once exchanged for treatment from the convoy’s locked medicine wagon.', allowedClasses: ALL_HERO_CLASSES, stats: { health: 4 }, value: 16, tags: ['medicine', 'caravan'], tier: 1, gates: { minChapter: 1 } }),
  defineCharm({ id: 'charm-witness-ring', name: 'Witness Ring', description: 'A plain iron ring marked inside with the date a frightened witness chose to speak publicly.', allowedClasses: ALL_HERO_CLASSES, stats: { will: 2 }, value: 24, tags: ['witness', 'evidence'], tier: 1, gates: { minChapter: 2 } }),
  defineCharm({ id: 'charm-royal-fletching', name: 'Royal Fletching Pin', description: 'A silver arrow pin whose workshop cuts match the royal ammunition found after the raid.', allowedClasses: ALL_HERO_CLASSES, stats: { attack: 2, focus: 2 }, value: 28, tags: ['royal', 'evidence'], tier: 1, gates: { minChapter: 2 } }),
  defineCharm({ id: 'charm-goblin-brass-button', name: 'Goblin Brass Button', description: 'A polished coat button traded among hidden-road couriers as proof that a bargain was honored.', allowedClasses: ALL_HERO_CLASSES, stats: { focus: 4, ward: 1 }, value: 32, tags: ['goblin', 'courier'], tier: 2, gates: { minChapter: 2 } }),
  defineCharm({ id: 'charm-redwater-peace-knot', name: 'Redwater Peace Knot', description: 'Human blue and orc red cords are tied around one river reed without cutting either strand.', allowedClasses: ALL_HERO_CLASSES, stats: { armor: 1, ward: 2, will: 2 }, value: 54, tags: ['redwater', 'peace'], tier: 2, gates: { minChapter: 4, minReputation: 10 } }),
  defineCharm({ id: 'charm-rukhar-name-bead', name: 'Rukhar’s Name Bead', description: 'A carved oath bead bearing Rukhar’s family mark and the plain terms of the Redwater truce.', allowedClasses: ['warrior', 'warden'], stats: { attack: 2, armor: 2, health: 4 }, value: 60, tags: ['orc', 'oath', 'companion'], tier: 2, gates: { minChapter: 4, questId: 'ch04-companion-the-cost-of-peace' } }),
  defineCharm({ id: 'charm-drowned-compass', name: 'Drowned Compass', description: 'A sealed river compass that points reliably after being recovered from a flooded courier bag.', allowedClasses: ['mage', 'warden'], stats: { focus: 5, ward: 2 }, value: 58, tags: ['river', 'navigation'], tier: 2, gates: { minChapter: 3 } }),
  defineCharm({ id: 'charm-ember-ledger-seal', name: 'Ember Ledger Seal', description: 'A heat-cracked ledger seal preserved because its serial number ties weapons to false buyers.', allowedClasses: ALL_HERO_CLASSES, stats: { will: 3, ward: 3 }, value: 76, tags: ['embervault', 'evidence'], tier: 3, gates: { minChapter: 5 } }),
  defineCharm({ id: 'charm-forgemasters-mark', name: 'Forgemaster’s Mark', description: 'A copper master mark that grows warm near unsafe metal and counterfeit armory fittings.', allowedClasses: ['warrior', 'mage'], stats: { attack: 3, armor: 2, ward: 1 }, value: 82, tags: ['forge', 'craft'], tier: 3, gates: { minChapter: 5 } }),
  defineCharm({ id: 'charm-mara-scout-badge', name: 'Mara’s Scout Badge', description: 'A blackened badge issued to scouts who returned with civilians rather than easy trophies.', allowedClasses: ['warden'], stats: { attack: 3, focus: 5 }, value: 98, tags: ['scout', 'companion'], tier: 3, gates: { minChapter: 5, questId: 'ch02-companion-mara-scouts-before-silver' } }),
  defineCharm({ id: 'charm-caldus-prayer-cord', name: 'Caldus’s Prayer Cord', description: 'A simple knotted cord counted during triage so fear never decides which patient comes first.', allowedClasses: ['mage', 'warrior'], stats: { health: 8, will: 3, ward: 2 }, value: 92, tags: ['healer', 'companion'], tier: 3, gates: { minChapter: 5, questId: 'ch05-companion-caldus-the-first-hostages' } }),
  defineCharm({ id: 'charm-lyra-cipher-lens', name: 'Lyra’s Cipher Lens', description: 'A ground crystal lens that exposes overwritten letters, ward joins, and convenient omissions.', allowedClasses: ['mage'], stats: { will: 6, focus: 5, ward: 2 }, value: 138, tags: ['cipher', 'companion'], tier: 4, gates: { minChapter: 6, questId: 'ch05-companion-lyra-and-the-embervault-ward' } }),
  defineCharm({ id: 'charm-talla-bell-coin', name: 'Talla’s Bell Coin', description: 'A pierced coin hung without a clapper, used to identify friends moving through hidden roads.', allowedClasses: ['mage', 'warden'], stats: { attack: 3, will: 3, focus: 5 }, value: 126, tags: ['goblin', 'companion'], tier: 4, gates: { minChapter: 6, questId: 'ch03-companion-talla-hides-the-refuge' } }),
  defineCharm({ id: 'charm-crownless-door-key', name: 'Crownless Door Key', description: 'A heavy keep key stamped with an office number omitted from every public floor plan.', allowedClasses: ALL_HERO_CLASSES, stats: { armor: 3, ward: 4, health: 5 }, value: 158, tags: ['key', 'crownless'], tier: 4, gates: { minChapter: 7, questId: 'ch07-main-inside-the-keep' } }),
  defineCharm({ id: 'charm-voss-broken-signet', name: 'Voss’s Broken Signet', description: 'Half of a command signet split across the crest after its authority was challenged in public.', allowedClasses: ALL_HERO_CLASSES, stats: { attack: 4, will: 5, armor: 2, ward: 3 }, value: 230, tags: ['signet', 'voss', 'evidence'], tier: 5, gates: { minChapter: 8, questId: 'ch08-main-who-keeps-the-crownless-keep' } }),
]);
