import { deepFreeze } from '../builders';
import { ALL_HERO_CLASSES, defineConsumable } from './types';

export const CHRONICLE1_CONSUMABLES = deepFreeze([
  defineConsumable({ id: 'consumable-field-bandage', name: 'Field Bandage', description: 'Clean folded linen and a wooden clasp close an ordinary wound without wasting travel time.', allowedClasses: ALL_HERO_CLASSES, stats: { health: 8 }, value: 10, tags: ['healing', 'field'], tier: 1, gates: { minChapter: 1 } }),
  defineConsumable({ id: 'consumable-greywatch-tonic', name: 'Greywatch Tonic', description: 'A sharp willow tonic eases pain and restores enough clarity to keep watch through the rain.', allowedClasses: ALL_HERO_CLASSES, stats: { health: 10, focus: 2 }, value: 18, tags: ['healing', 'greywatch'], tier: 1, gates: { minChapter: 1 } }),
  defineConsumable({ id: 'consumable-bitterroot-tea', name: 'Bitterroot Tea', description: 'A bitter roadside tea settles shaking hands and returns attention to the immediate problem.', allowedClasses: ALL_HERO_CLASSES, stats: { focus: 5 }, value: 12, tags: ['focus', 'herbal'], tier: 1, gates: { minChapter: 1 } }),
  defineConsumable({ id: 'consumable-smoke-bomb', name: 'Smoke Bomb', description: 'A clay smoke charge creates one breathing space to regroup, bind a cut, and recover focus.', allowedClasses: ALL_HERO_CLASSES, stats: { focus: 4 }, value: 16, tags: ['focus', 'escape'], tier: 1, gates: { minChapter: 1 } }),
  defineConsumable({ id: 'consumable-caltrop-pouch', name: 'Caltrop Pouch', description: 'A small pouch of iron points buys a careful traveler enough distance to steady their nerves.', allowedClasses: ALL_HERO_CLASSES, stats: { focus: 3 }, value: 14, tags: ['focus', 'road'], tier: 1, gates: { minChapter: 1 } }),
  defineConsumable({ id: 'consumable-lamp-oil', name: 'Clear Lamp Oil', description: 'Clean-burning lamp oil restores confidence in tunnels where every uncertain shadow costs time.', allowedClasses: ALL_HERO_CLASSES, stats: { focus: 4 }, value: 12, tags: ['focus', 'light'], tier: 1, gates: { minChapter: 1 } }),
  defineConsumable({ id: 'consumable-antivenom', name: 'Marsh Antivenom', description: 'A measured herb tincture slows common marsh venom while supporting the body through the fever.', allowedClasses: ALL_HERO_CLASSES, stats: { health: 9 }, value: 28, tags: ['healing', 'antivenom'], tier: 2, gates: { minChapter: 2 } }),
  defineConsumable({ id: 'consumable-marsh-salts', name: 'Marsh Wake Salts', description: 'Pungent mineral salts clear river fog from the head after a cold crossing or sudden blow.', allowedClasses: ALL_HERO_CLASSES, stats: { focus: 7 }, value: 26, tags: ['focus', 'drowned-road'], tier: 2, gates: { minChapter: 3 } }),
  defineConsumable({ id: 'consumable-orc-field-broth', name: 'Free Host Field Broth', description: 'A salty orc campaign broth restores warmth, strength, and the patience needed for another mile.', allowedClasses: ALL_HERO_CLASSES, stats: { health: 12, focus: 4 }, value: 34, tags: ['healing', 'orc'], tier: 2, gates: { minChapter: 3 } }),
  defineConsumable({ id: 'consumable-redwater-stimulant', name: 'Redwater Stimulant', description: 'A guild apothecary’s measured stimulant sharpens attention without disguising exhaustion.', allowedClasses: ALL_HERO_CLASSES, stats: { focus: 9 }, value: 38, tags: ['focus', 'redwater'], tier: 2, gates: { minChapter: 4 } }),
  defineConsumable({ id: 'consumable-warding-chalk', name: 'Warding Chalk Dose', description: 'Crushed warding chalk mixed in water steadies concentration before crossing a hostile seal.', allowedClasses: ALL_HERO_CLASSES, stats: { focus: 8 }, value: 42, tags: ['focus', 'ward'], tier: 2, gates: { minChapter: 4 } }),
  defineConsumable({ id: 'consumable-magefire-flask', name: 'Magefire Recovery Flask', description: 'A safely diluted magefire cordial restores breath and focus after exposure to furnace magic.', allowedClasses: ALL_HERO_CLASSES, stats: { health: 4, focus: 10 }, value: 58, tags: ['healing', 'focus', 'fire'], tier: 3, gates: { minChapter: 5 } }),
  defineConsumable({ id: 'consumable-frost-salve', name: 'Frost Salve', description: 'Cold mineral salve calms burns, swelling, and the deep ache left by overheated armor.', allowedClasses: ALL_HERO_CLASSES, stats: { health: 14 }, value: 60, tags: ['healing', 'cold'], tier: 3, gates: { minChapter: 5 } }),
  defineConsumable({ id: 'consumable-ember-draught', name: 'Ember Draught', description: 'A warm copper draught returns circulation and disciplined focus after a punishing fight.', allowedClasses: ALL_HERO_CLASSES, stats: { health: 8, focus: 9 }, value: 70, tags: ['healing', 'focus', 'embervault'], tier: 3, gates: { minChapter: 5 } }),
  defineConsumable({ id: 'consumable-burn-paste', name: 'Foreman’s Burn Paste', description: 'Thick mine paste seals damaged skin and keeps grit away until proper treatment is possible.', allowedClasses: ALL_HERO_CLASSES, stats: { health: 16 }, value: 64, tags: ['healing', 'embervault'], tier: 3, gates: { minChapter: 5 } }),
  defineConsumable({ id: 'consumable-focus-incense', name: 'Measured Focus Incense', description: 'One marked stick burns quickly and restores a mage’s rhythm without filling the road with smoke.', allowedClasses: ALL_HERO_CLASSES, stats: { focus: 12 }, value: 72, tags: ['focus', 'conclave'], tier: 3, gates: { minChapter: 5 } }),
  defineConsumable({ id: 'consumable-armor-pitch', name: 'Medicinal Armor Pitch', description: 'Warm resin braces bruised ribs beneath armor and reduces pain during the next hard movement.', allowedClasses: ALL_HERO_CLASSES, stats: { health: 18 }, value: 98, tags: ['healing', 'siege'], tier: 4, gates: { minChapter: 6 } }),
  defineConsumable({ id: 'consumable-whetstone-kit', name: 'Campaign Whetstone Kit', description: 'A short maintenance ritual restores control and confidence before steel is drawn again.', allowedClasses: ALL_HERO_CLASSES, stats: { focus: 13 }, value: 100, tags: ['focus', 'craft'], tier: 4, gates: { minChapter: 6 } }),
  defineConsumable({ id: 'consumable-hearty-ration', name: 'Hearty March Ration', description: 'Dense oatcake, dried meat, and sour fruit restore the body without requiring a campfire.', allowedClasses: ALL_HERO_CLASSES, stats: { health: 15, focus: 7 }, value: 75, tags: ['healing', 'food'], tier: 3, gates: { minChapter: 5 } }),
  defineConsumable({ id: 'consumable-blackroot-brew', name: 'Blackroot Brew', description: 'A carefully strained root brew restores stamina and focus without the dangerous raw sap.', allowedClasses: ALL_HERO_CLASSES, stats: { health: 10, focus: 12 }, value: 112, tags: ['healing', 'focus', 'herbal'], tier: 4, gates: { minChapter: 6 } }),
  defineConsumable({ id: 'consumable-healing-poultice', name: 'Siege Healing Poultice', description: 'A broad hot poultice treats deep bruising and closes torn skin during a brief halt.', allowedClasses: ALL_HERO_CLASSES, stats: { health: 22 }, value: 118, tags: ['healing', 'siege'], tier: 4, gates: { minChapter: 7 } }),
  defineConsumable({ id: 'consumable-cleansing-herbs', name: 'Cleansing Herb Bundle', description: 'Bitter leaves and clean salts restore strength after smoke, foul water, or spoiled provisions.', allowedClasses: ALL_HERO_CLASSES, stats: { health: 14, focus: 10 }, value: 126, tags: ['healing', 'focus', 'cleanse'], tier: 4, gates: { minChapter: 7 } }),
  defineConsumable({ id: 'consumable-courage-cordial', name: 'Courage Cordial', description: 'A final reserve cordial steadies thought before a public confrontation that cannot be undone.', allowedClasses: ALL_HERO_CLASSES, stats: { focus: 16 }, value: 168, tags: ['focus', 'crownless'], tier: 5, gates: { minChapter: 8 } }),
  defineConsumable({ id: 'consumable-last-light-phial', name: 'Last Light Phial', description: 'A sealed golden remedy restores a badly spent traveler before the keep’s last doors open.', allowedClasses: ALL_HERO_CLASSES, stats: { health: 26, focus: 14 }, value: 210, tags: ['healing', 'focus', 'crownless'], tier: 5, gates: { minChapter: 8, questId: 'ch08-main-the-marshal-and-the-banner' } }),
]);
