import { deepFreeze } from '../builders';
import { ALL_HERO_CLASSES, defineTool } from './types';

/**
 * Reusable field kits and single-use tactical scripts. They retain the legacy
 * `scroll` category so the existing inventory understands their stack rules.
 */
export const CHRONICLE1_TOOLS = deepFreeze([
  defineTool({
    id: 'scroll-counterseal',
    name: 'Counterseal Script',
    description: 'A copied sequence of ward marks that reinforces a traveler against one deliberate magical breach.',
    allowedClasses: ALL_HERO_CLASSES,
    stats: { ward: 6 },
    value: 74,
    tags: ['scroll', 'ward', 'counterseal'],
    tier: 3,
    gates: { minChapter: 5 },
    useContexts: ['combat'],
  }),
  defineTool({
    id: 'scroll-hushed-step',
    name: 'Hushed Step Script',
    description: 'A short field incantation steadies breathing and masks the next careful movement through hostile ground.',
    allowedClasses: ALL_HERO_CLASSES,
    stats: { will: 4 },
    value: 44,
    tags: ['scroll', 'stealth', 'road'],
    tier: 2,
    gates: { minChapter: 3 },
    useContexts: ['combat'],
  }),
  defineTool({
    id: 'scroll-breaking-ward',
    name: 'Wardbreaking Script',
    description: 'A dangerous but measured formula directs force into the weakest seam of an enemy ward or shield line.',
    allowedClasses: ALL_HERO_CLASSES,
    stats: { attack: 3, will: 5 },
    value: 128,
    tags: ['scroll', 'siege', 'wardbreak'],
    tier: 4,
    gates: { minChapter: 6 },
    useContexts: ['combat'],
  }),
  defineTool({
    id: 'scroll-roadward',
    name: 'Roadward Script',
    description: 'A practical protection rite hardens resolve and armor before a company crosses an exposed stretch of road.',
    allowedClasses: ALL_HERO_CLASSES,
    stats: { armor: 2, ward: 4 },
    value: 70,
    tags: ['scroll', 'protection', 'road'],
    tier: 3,
    gates: { minChapter: 4 },
    useContexts: ['combat'],
  }),
  defineTool({
    id: 'tool-lockpick-roll',
    name: 'Lockpick Roll',
    description: 'Files, hooks, and tension bars sit in marked sleeves for opening ordinary locks without noisy damage.',
    allowedClasses: ALL_HERO_CLASSES,
    stats: {},
    value: 34,
    tags: ['tool', 'locks', 'infiltration'],
    tier: 2,
    gates: { minChapter: 3 },
  }),
  defineTool({
    id: 'tool-field-repair-kit',
    name: 'Field Repair Kit',
    description: 'Spare rivets, waxed cord, and compact pliers keep weapons and armor dependable between safe camps.',
    allowedClasses: ALL_HERO_CLASSES,
    stats: {},
    value: 68,
    tags: ['tool', 'repair', 'campcraft'],
    tier: 3,
    gates: { minChapter: 5 },
  }),
  defineTool({
    id: 'tool-surveyors-kit',
    name: "Surveyor's Kit",
    description: 'A sighting cord, wax tablet, and folding rule help identify sound crossings and defensible ground.',
    allowedClasses: ALL_HERO_CLASSES,
    stats: {},
    value: 62,
    tags: ['tool', 'survey', 'navigation'],
    tier: 3,
    gates: { minChapter: 4 },
  }),
  defineTool({
    id: 'tool-signal-whistle',
    name: 'Signal Whistle',
    description: 'A plain brass whistle carries agreed road signals farther than a shouted warning in bad weather.',
    allowedClasses: ALL_HERO_CLASSES,
    stats: {},
    value: 16,
    tags: ['tool', 'signal', 'scouting'],
    tier: 1,
    gates: { minChapter: 1 },
  }),
]);
