import { defineScene } from '../../builders';

export const CH01_COMPANION = Object.freeze([
  defineScene({
    id: 'ch01-companion-mara-measures-the-road',
    chapterId: 'ch01',
    region: 'gloamwood',
    slot: 21,
    type: 'companion',
    family: 'mara-first-meeting',
    relationship: { kind: 'companion', companionId: 'mara' },
    weight: 18,
    pacing: 'quiet',
    illustrationId: 'scene-ch01-companion-mara-measures-the-road',
    title: 'Mara Measures the Road',
    narrative: [
      'A border scout waits beside a cut milestone, counting wagon ruts with a length of knotted cord. She names herself Mara Vey and says three armed groups used this road during the night.',
      'Mara offers a safer turn through the birches if the caravan can spare time. The direct road is faster, but whoever passed before you will know it was followed.',
    ],
    eligibility: { routes: ['kings-road', 'old-forest'], minLevel: 1, maxLevel: 2, excludedFlags: ['mara-met'] },
    requirements: [],
    exclusions: [],
    cooldownRuns: 3,
    oneShot: true,
    followUps: ['ch01-companion-mara-at-the-burning-bridge'],
    callbackPromises: [],
    choices: [
      {
        id: 'ch01-choice-follow-maras-birch-track',
        label: 'Follow Mara\'s birch track',
        detail: 'Trust an unknown scout and lose road speed, but avoid the clearest line of pursuit.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'mara-met' },
          { type: 'companion-loyalty', companionId: 'mara', amount: 3 },
          { type: 'threat', amount: -1 },
        ],
        outcome: 'Mara guides the wagons through firm woodland and leaves fresh cut marks for anyone forced to follow.',
      },
      {
        id: 'ch01-choice-keep-to-route-seven',
        label: 'Keep to Route Seven',
        detail: 'Hold the official road and preserve time, while accepting that the convoy remains easy to track.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'mara-met' },
          { type: 'companion-loyalty', companionId: 'mara', amount: -1 },
          { type: 'threat', amount: 1 },
        ],
        outcome: 'Mara falls in beside the rear wagon long enough to see whether the road proves you right.',
      },
    ],
  }),
  defineScene({
    id: 'ch01-companion-talla-and-the-spared-courier',
    chapterId: 'ch01',
    region: 'gloamwood',
    slot: 38,
    type: 'companion',
    family: 'talla-spared-courier',
    relationship: { kind: 'companion', companionId: 'talla' },
    weight: 24,
    pacing: 'quiet',
    illustrationId: 'scene-ch01-companion-talla-and-the-spared-courier',
    title: 'Talla and the Spared Courier',
    narrative: [
      'A young goblin courier is caught in a wire snare behind the tollhouse. He carries no weapon, only a slate marked with food deliveries and a warning about armed humans wearing borrowed colors.',
      'Talla Quickhand steps from the hazel brush with an empty crossbow. She asks you to cut him down before the caravan guards decide that a frightened courier must be an ambusher.',
    ],
    eligibility: { routes: ['kings-road', 'old-forest', 'ruined-pass'], minLevel: 1, maxLevel: 2 },
    requirements: [],
    exclusions: [],
    cooldownRuns: 3,
    oneShot: true,
    followUps: ['ch01-companion-talla-names-the-price'],
    callbackPromises: [],
    choices: [
      {
        id: 'ch01-choice-cut-the-courier-free',
        label: 'Cut the courier free',
        detail: 'Release a possible scout without questioning him first, risking anger from the armed caravan hands.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'talla-met' },
          { type: 'flag', operation: 'add', flagId: 'goblin-courier-spared' },
          { type: 'companion-quest', companionId: 'talla', stage: 1 },
          { type: 'companion-loyalty', companionId: 'talla', amount: 8 },
        ],
        outcome: 'The courier gives Talla his slate and runs west; two guards lower their spears only after you order it.',
      },
      {
        id: 'ch01-choice-turn-the-courier-over',
        label: 'Turn the courier over',
        detail: 'Let the guards question him under restraint, but risk destroying Talla\'s trust before it begins.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'talla-met' },
          { type: 'flag', operation: 'add', flagId: 'talla-betrayed' },
          { type: 'companion-quest', companionId: 'talla', stage: 1 },
          { type: 'companion-loyalty', companionId: 'talla', amount: -10 },
        ],
        outcome: 'Talla disappears into the brush while the guards bind the courier and take his slate.',
      },
    ],
  }),
  defineScene({
    id: 'ch01-faction-jorys-seal-lesson',
    chapterId: 'ch01',
    region: 'gloamwood',
    slot: 56,
    type: 'companion',
    family: 'dispatch-provenance',
    relationship: { kind: 'faction', factionId: 'greywatch' },
    weight: 30,
    pacing: 'quiet',
    illustrationId: 'scene-ch01-faction-jorys-seal-lesson',
    title: 'Jory\'s Seal Lesson',
    narrative: [
      'While the wounded are moved, Jory shows you the dispatch seal: a split tower above the number seven. The route code, wax mixture, and clerk\'s countermark identify Greywatch as the intended recipient.',
      'He admits that the pierced tube makes him a target. A duplicate depot chit and Greywatch\'s receiving register could confirm the convoy if he does not survive.',
    ],
    eligibility: { routes: ['kings-road', 'old-forest', 'ruined-pass'], minLevel: 1, maxLevel: 2 },
    requirements: [],
    exclusions: [],
    cooldownRuns: 2,
    oneShot: true,
    followUps: ['ch02-journey-jorys-duplicate-chit'],
    callbackPromises: [],
    choices: [
      {
        id: 'ch01-choice-copy-the-route-code',
        label: 'Copy the route code',
        detail: 'Spend time making a second record, but reduce the risk that one stolen tube erases the proof.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'route-seven-code-copied' },
          { type: 'evidence', operation: 'add', evidenceId: 'route-seven-dispatch' },
        ],
        outcome: 'Jory writes the code inside your map case and marks the Greywatch quartermaster as its receiver.',
      },
      {
        id: 'ch01-choice-hide-the-tube-on-jory',
        label: 'Hide the tube on Jory',
        detail: 'Keep the dispatch with its trained witness, but accept the risk that both can be lost together.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'jory-kept-dispatch' },
          { type: 'companion-loyalty', companionId: 'mara', amount: 1 },
        ],
        outcome: 'Jory straps the waxed tube beneath his shirt and repeats the receiving code until you know it by memory.',
      },
    ],
  }),
  defineScene({
    id: 'ch01-companion-mara-at-the-burning-bridge',
    chapterId: 'ch01',
    region: 'gloamwood',
    slot: 65,
    type: 'companion',
    family: 'mara-civilian-duty',
    relationship: { kind: 'companion', companionId: 'mara' },
    weight: 30,
    pacing: 'recovery',
    illustrationId: 'scene-ch01-companion-mara-at-the-burning-bridge',
    title: 'Mara at the Burning Bridge',
    narrative: [
      'On the far bank, Mara binds the toll officer\'s wound and counts the rescued families by name. She says scouts are judged by who reaches safety, not by how many enemies they kill.',
      'The bridge supports will fail soon. One injured villager still cannot walk, and the convoy has room only if a medicine crate is moved into the rain.',
    ],
    eligibility: { routes: ['kings-road', 'old-forest', 'ruined-pass'], minLevel: 1, maxLevel: 2, requiredFlags: ['mara-met'] },
    requirements: [],
    exclusions: [],
    cooldownRuns: 3,
    oneShot: true,
    followUps: ['ch02-companion-mara-the-broken-command'],
    callbackPromises: [],
    choices: [
      {
        id: 'ch01-choice-make-room-for-the-injured',
        label: 'Make room for the injured',
        detail: 'Expose one sealed medicine crate to rain so the wounded villager can ride safely.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'greywatch-civilians-protected' },
          { type: 'companion-quest', companionId: 'mara', stage: 1 },
          { type: 'companion-loyalty', companionId: 'mara', amount: 7 },
        ],
        outcome: 'Mara covers the crate with her cloak and lifts the villager onto the wagon beside Jory.',
        nextSceneId: 'ch01-journey-the-wagon-or-the-rope',
        continueLabel: 'Clear the last burning support',
      },
      {
        id: 'ch01-choice-leave-a-litter-party',
        label: 'Leave a litter party',
        detail: 'Keep every medicine case protected, but split three defenders from the caravan to carry the wounded.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'bridge-litter-party-left' },
          { type: 'companion-quest', companionId: 'mara', stage: 1 },
          { type: 'companion-loyalty', companionId: 'mara', amount: -2 },
          { type: 'threat', amount: 1 },
        ],
        outcome: 'Three volunteers remain with a canvas litter while Mara watches the smaller convoy move north.',
        nextSceneId: 'ch01-journey-the-wagon-or-the-rope',
        continueLabel: 'Clear the last burning support',
      },
    ],
  }),
  defineScene({
    id: 'ch01-companion-talla-names-the-price',
    chapterId: 'ch01',
    region: 'gloamwood',
    slot: 81,
    type: 'companion',
    family: 'talla-secret-bargain',
    relationship: { kind: 'companion', companionId: 'talla' },
    weight: 28,
    pacing: 'quiet',
    illustrationId: 'scene-ch01-companion-talla-names-the-price',
    title: 'Talla Names the Price',
    narrative: [
      'Talla returns after the staged banner is found. Her courier saw uniformed humans paying raiders at an abandoned lime kiln outside Greywatch.',
      'She will mark the kiln on your map if you promise not to reveal the courier\'s food route. The same path supplies a hidden goblin refuge, and soldiers would close it if they knew.',
    ],
    eligibility: { routes: ['old-forest', 'kings-road'], minLevel: 1, maxLevel: 2, requiredFlags: ['talla-met'], excludedFlags: ['talla-betrayed'] },
    requirements: [],
    exclusions: [],
    cooldownRuns: 3,
    oneShot: true,
    followUps: ['ch02-companion-talla-keeps-the-bargain'],
    callbackPromises: [],
    choices: [
      {
        id: 'ch01-choice-accept-tallas-secret-bargain',
        label: 'Accept Talla\'s secret bargain',
        detail: 'Gain a lead on the raiders, but withhold a useful supply route from Greywatch\'s soldiers.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'secret-bargain-started' },
          { type: 'companion-loyalty', companionId: 'talla', amount: 5 },
          {
            type: 'callback',
            promise: {
              targetEventId: 'ch02-companion-talla-keeps-the-bargain',
              deadline: { chapterId: 'ch02', slot: 31 },
            },
          },
        ],
        outcome: 'Talla scratches the kiln beside a quarry mark and makes you repeat the promise without witnesses.',
      },
      {
        id: 'ch01-choice-demand-an-open-report',
        label: 'Demand an open report',
        detail: 'Give Greywatch every route detail, but risk exposing the courier and the families he supplies.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'talla-betrayed' },
          { type: 'companion-loyalty', companionId: 'talla', amount: -8 },
          { type: 'faction', factionId: 'greywatch', amount: 1 },
        ],
        outcome: 'Talla gives you the kiln location, then leaves before you can ask where her people will go.',
      },
    ],
  }),
]);
