import { defineScene } from '../../builders';

const ALL_ROUTES = ['kings-road', 'old-forest', 'ruined-pass'] as const;
const COMMON = {
  chapterId: 'ch01' as const,
  region: 'gloamwood' as const,
  weight: 100,
  eligibility: { routes: ALL_ROUTES, minLevel: 1, maxLevel: 2 },
  requirements: [],
  exclusions: [],
  cooldownRuns: 0,
  oneShot: true,
  followUps: [],
  callbackPromises: [],
};

export const CH01_LIVING_ROAD_ODDITIES = Object.freeze([
  defineScene({
    ...COMMON,
    id: 'ch01-living-warning-tree',
    slot: 22,
    type: 'journey',
    journeySubtype: 'investigation',
    family: 'living-warning-tree',
    weight: 4,
    pacing: 'quiet',
    illustrationId: 'scene-ch01-living-warning-tree',
    title: 'The Warning Tree',
    narrative: [
      'A young goblin hangs by a broad leather harness from an old oak beside the road. The body is still, the knot is military, and three food slates are nailed at eye level beneath his feet. No blood marks the bark. Small footprints approach the tree, but only deep round punctures lead away.',
    ],
    eligibility: { routes: ALL_ROUTES, minLevel: 1, maxLevel: 2 },
    requirements: [
      { type: 'flag', flagId: 'warning-tree-entry-ready' },
      { type: 'flag', flagId: 'warning-tree-route-chosen' },
    ],
    exclusions: [{ type: 'flag', flagId: 'warning-tree-resolved' }],
    dialogue: [
      {
        speakerName: 'Jory Fen',
        text: 'Those slates count flour and lamp oil. Someone killed a courier and left his route on display.',
        environmentIllustrationId: 'scene-ch01-living-warning-tree',
      },
      {
        speakerName: 'Mara Vey',
        text: 'Or left him where another courier would have to look up.',
        requirements: [{ type: 'flag', flagId: 'mara-met' }],
        environmentIllustrationId: 'scene-ch01-living-warning-tree',
      },
    ],
    choices: [
      {
        id: 'ch01-choice-warning-tree-read-the-ground',
        label: 'Read the ground before touching him',
        detail: 'Hold the wagons beyond bow range while preserving every track beneath the oak.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'warning-tree-ground-preserved' },
          { type: 'threat', amount: 1 },
        ],
        outcome: 'The wagons halt beyond bow range while you mark every print, puncture, and broken fern.',
        nextSceneId: 'ch01-living-warning-tree-choice',
        continueLabel: 'Examine the warning',
      },
      {
        id: 'ch01-choice-warning-tree-cut-him-down-now',
        label: 'Cut him down now',
        detail: 'Give the courier immediate respect, but touch the staged scene before reading its tracks.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'warning-tree-body-lowered' },
          { type: 'tension', amount: 1 },
        ],
        outcome: "The harness lowers without tightening, revealing a bronze tally hidden against the goblin's coat.",
        nextSceneId: 'ch01-living-warning-tree-choice',
        continueLabel: 'See what the harness concealed',
      },
      {
        id: 'ch01-choice-warning-tree-set-an-ambush',
        label: 'Prepare for whoever returns',
        detail: 'Spend one class resource to hide the convoy while leaving the warning untouched.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'warning-tree-ambush-ready' },
          { type: 'vitals', resource: -1 },
        ],
        outcome: 'Guards move the wagons behind the bend and leave the tree exactly as it was.',
        nextSceneId: 'ch01-living-warning-tree-choice',
        continueLabel: 'Wait beneath cover',
      },
    ],
  }),
  defineScene({
    ...COMMON,
    id: 'ch01-living-warning-tree-choice',
    slot: 23,
    type: 'combat',
    family: 'living-warning-tree-choice',
    pacing: 'danger',
    illustrationId: 'scene-ch01-living-warning-tree-choice',
    title: 'Punctures in the Leaf Mold',
    narrative: [
      'The round marks are from iron climbing spikes strapped to human boots. Two masked road zealots return along the upper branches, moving above the ordinary trail. The goblin was a courier, and the slates were bait for anyone who knew his route.',
    ],
    requirements: [{ type: 'flag', flagId: 'warning-tree-route-chosen' }],
    choices: [
      {
        id: 'ch01-choice-warning-tree-trace-the-spikes',
        label: 'Trace the spikes and spring their snare',
        detail: "Use Cunning against difficulty 4 to turn the zealots' own return rope against them.",
        check: {
          stat: 'cunning',
          difficulty: 4,
          modifiers: [
            {
              label: 'Ground preserved +10',
              amount: 10,
              requirements: [{ type: 'flag', flagId: 'warning-tree-ground-preserved' }],
            },
            {
              label: 'Ambush ready +10',
              amount: 10,
              requirements: [{ type: 'flag', flagId: 'warning-tree-ambush-ready' }],
            },
          ],
          success: {
            outcome: "You pull the zealots' return rope from below, stranding them in the crown until the convoy passes.",
            effects: [
              { type: 'flag', operation: 'add', flagId: 'warning-tree-executioners-identified' },
              { type: 'flag', operation: 'add', flagId: 'warning-tree-clue-held' },
              { type: 'evidence', operation: 'add', evidenceId: 'thorn-road-tally' },
              { type: 'xp', amount: 20, source: 'story' },
              { type: 'threat', amount: -1 },
            ],
            nextSceneId: 'ch01-living-warning-tree-aftermath',
            continueLabel: 'Question them from the ground',
          },
          failure: {
            outcome: 'A hidden branch loop catches a guard and the zealots descend behind you.',
            effects: [
              { type: 'vitals', health: -3 },
              { type: 'flag', operation: 'add', flagId: 'warning-tree-fight-committed' },
            ],
            combatEncounterId: 'enc-ch01-warning-tree-penitents',
            nextSceneId: 'ch01-living-warning-tree-aftermath',
            continueLabel: 'Fight beneath the oak',
          },
        },
      },
      {
        id: 'ch01-choice-warning-tree-demand-a-name',
        label: "Demand the courier's name and sentence",
        detail: 'Use Will against difficulty 4 to force the masked zealots to name their victim and employer.',
        check: {
          stat: 'will',
          difficulty: 4,
          modifiers: [
            {
              label: 'Body given respect +5',
              amount: 5,
              requirements: [{ type: 'flag', flagId: 'warning-tree-body-lowered' }],
            },
          ],
          success: {
            outcome: 'One zealot admits the slates serve hidden goblin families and names a paid officer at the tollhouse.',
            effects: [
              { type: 'evidence', operation: 'add', evidenceId: 'warning-tree-officer-testimony' },
              { type: 'flag', operation: 'add', flagId: 'warning-tree-witness-clue' },
              { type: 'flag', operation: 'add', flagId: 'warning-tree-clue-held' },
              { type: 'xp', amount: 18, source: 'quest' },
            ],
            nextSceneId: 'ch01-living-warning-tree-aftermath',
            continueLabel: 'Carry the named clue',
          },
          failure: {
            outcome: 'The zealots answer by dropping weighted hooks into the guards.',
            effects: [
              { type: 'vitals', resource: -2 },
              { type: 'threat', amount: 1 },
              { type: 'flag', operation: 'add', flagId: 'warning-tree-fight-committed' },
            ],
            combatEncounterId: 'enc-ch01-warning-tree-penitents',
            nextSceneId: 'ch01-living-warning-tree-aftermath',
            continueLabel: 'Break their descent',
          },
        },
      },
      {
        id: 'ch01-choice-warning-tree-cut-the-return-rope',
        label: 'Cut their return rope and leave',
        detail: 'Abandon the interrogation and buy the convoy a clean mile without battle.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'warning-tree-avoided' },
          { type: 'threat', amount: -2 },
        ],
        outcome: 'The zealots cannot descend without abandoning masks and weapons, buying the convoy a clean mile.',
        nextSceneId: 'ch01-living-warning-tree-aftermath',
        continueLabel: 'Take the courier from their road',
      },
    ],
  }),
  defineScene({
    ...COMMON,
    id: 'ch01-living-warning-tree-aftermath',
    slot: 24,
    type: 'journey',
    journeySubtype: 'moral-choice',
    family: 'living-warning-tree-aftermath',
    pacing: 'quiet',
    illustrationId: 'scene-ch01-living-warning-tree-aftermath',
    title: "The Courier's Bronze Tally",
    narrative: [
      "The leather harness carries a bronze tally stamped with three family marks and the same food totals as the slates. It can guide supplies, prove the killing's purpose, or be buried with the courier so no patrol can follow it.",
    ],
    requirements: [{ type: 'flag', flagId: 'warning-tree-route-chosen' }],
    choices: [
      {
        id: 'ch01-choice-warning-tree-preserve-the-tally',
        label: 'Preserve the tally as evidence',
        detail: 'Seal the food record while keeping the hidden families out of the public ledger.',
        requirements: [{ type: 'flag', flagId: 'warning-tree-clue-held' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'warning-tree-resolved' },
          { type: 'evidence', operation: 'add', evidenceId: 'hidden-road-food-tally' },
          { type: 'item', operation: 'grant', itemId: 'charm-warning-tree-knot', quantity: 1, destination: 'unbanked-loot' },
          { type: 'xp', amount: 10, source: 'quest' },
        ],
        outcome: 'Jory seals the tally while leaving the family marks out of his public ledger.',
        nextSceneId: 'ch01-main-the-empty-tollhouse',
        continueLabel: 'Enter the empty tollhouse',
      },
      {
        id: 'ch01-choice-warning-tree-return-the-tally',
        label: 'Leave the tally at a courier mark',
        detail: 'Warn the hidden couriers without giving Greywatch their food route.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'warning-tree-resolved' },
          { type: 'flag', operation: 'add', flagId: 'goblin-couriers-warned' },
          { type: 'faction', factionId: 'greywatch', amount: -1 },
          { type: 'tension', amount: -1 },
        ],
        outcome: 'You tuck the tally beneath a cut birch sign where another courier can recover it without approaching the tree.',
        nextSceneId: 'ch01-main-the-empty-tollhouse',
        continueLabel: 'Enter the empty tollhouse',
      },
      {
        id: 'ch01-choice-warning-tree-bury-the-route',
        label: 'Bury courier and route together',
        detail: 'Leave no family mark for soldiers to copy and give the courier a roadside cairn.',
        requirements: [{ type: 'flag', flagId: 'warning-tree-body-lowered' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'warning-tree-resolved' },
          { type: 'flag', operation: 'add', flagId: 'warning-tree-route-buried' },
          { type: 'vitals', health: 1 },
        ],
        outcome: 'The convoy builds a shallow stone cairn and leaves no family mark for soldiers to copy.',
        nextSceneId: 'ch01-main-the-empty-tollhouse',
        continueLabel: 'Enter the empty tollhouse',
      },
    ],
  }),
  defineScene({
    ...COMMON,
    id: 'ch01-living-armor-that-knelt',
    slot: 43,
    type: 'journey',
    journeySubtype: 'investigation',
    family: 'living-kneeling-armor',
    weight: 3,
    pacing: 'quiet',
    illustrationId: 'scene-ch01-living-armor-that-knelt',
    title: 'The Armor That Knelt',
    narrative: [
      'In a rain-cut hollow, a sealed suit of old levy plate kneels with both hands around a rusted sword. Mud has not entered its joints. When the nearest medicine wagon rolls forward, the helmet turns and the sword point scratches one word into the clay: "Name."',
    ],
    eligibility: { routes: ALL_ROUTES, minLevel: 1, maxLevel: 2 },
    requirements: [
      { type: 'flag', flagId: 'kneeling-armor-entry-ready' },
      { type: 'flag', flagId: 'kneeling-armor-route-chosen' },
    ],
    exclusions: [{ type: 'flag', flagId: 'kneeling-armor-resolved' }],
    dialogue: [
      {
        speakerName: 'Voice Inside the Helm',
        text: 'Name the officer who sent the dead north.',
        environmentIllustrationId: 'scene-ch01-living-armor-that-knelt',
      },
      {
        speakerName: 'Jory Fen',
        text: 'That plate predates my grandfather.',
        environmentIllustrationId: 'scene-ch01-living-armor-that-knelt',
      },
    ],
    choices: [
      {
        id: 'ch01-choice-armor-read-the-service-marks',
        label: 'Read its service marks from a distance',
        detail: 'Spend one class resource to identify the levy company without approaching the sword.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'kneeling-armor-marks-read' },
          { type: 'vitals', resource: -1 },
        ],
        outcome: 'The breastplate number matches a levy company lost while guarding the old barrow road.',
        nextSceneId: 'ch01-living-armor-that-knelt-test',
        continueLabel: 'Answer the armor',
      },
      {
        id: 'ch01-choice-armor-wedge-the-joints',
        label: 'Wedge the knee and sword arm',
        detail: 'Risk a close approach to pin the exposed joints before opening the harness.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'kneeling-armor-joints-wedged' },
          { type: 'threat', amount: 1 },
        ],
        outcome: 'Guards slide cart pins into the exposed joints while the suit remains deliberately still.',
        nextSceneId: 'ch01-living-armor-that-knelt-test',
        continueLabel: 'Open the sealed harness',
      },
      {
        id: 'ch01-choice-armor-give-it-the-road',
        label: 'Back the medicine away and go around',
        detail: 'Keep your distance and accept that the occupied armor remains beside the road.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'kneeling-armor-avoided' },
          { type: 'tension', amount: 1 },
        ],
        outcome: 'The visor follows the wagon while the convoy begins edging around the hollow, but the suit does not rise.',
        nextSceneId: 'ch01-living-armor-that-knelt-test',
        continueLabel: 'Pass beyond its reach',
      },
    ],
  }),
  defineScene({
    ...COMMON,
    id: 'ch01-living-armor-that-knelt-test',
    slot: 44,
    type: 'combat',
    family: 'living-kneeling-armor-test',
    pacing: 'danger',
    illustrationId: 'scene-ch01-living-armor-that-knelt-test',
    title: 'The Occupant Behind the Visor',
    requirements: [{ type: 'flag', flagId: 'kneeling-armor-route-chosen' }],
    narrative: [
      'The visor opens one finger-width. Inside is a dead levy soldier bound upright by old harness straps, jaw working around a corroded command token. The armor is not empty and not a wandering spirit. A corpse is still obeying its last posted order.',
    ],
    choices: [
      {
        id: 'ch01-choice-armor-answer-with-the-route-code',
        label: "Answer with Route Seven's receiving name",
        detail: 'Use Will against difficulty 4 to replace the dead order with Greywatch lawful command.',
        exclusions: [{ type: 'flag', flagId: 'kneeling-armor-avoided' }],
        check: {
          stat: 'will',
          difficulty: 4,
          modifiers: [
            {
              label: 'Service marks understood +10',
              amount: 10,
              requirements: [{ type: 'flag', flagId: 'kneeling-armor-marks-read' }],
            },
          ],
          success: {
            outcome: "The dead soldier accepts Greywatch's quartermaster as the current lawful receiver and releases the token.",
            effects: [
              { type: 'flag', operation: 'add', flagId: 'kneeling-armor-dismissed' },
              { type: 'flag', operation: 'add', flagId: 'kneeling-armor-peaceful' },
              { type: 'evidence', operation: 'add', evidenceId: 'old-levy-command-token' },
              { type: 'xp', amount: 22, source: 'story' },
            ],
            nextSceneId: 'ch01-living-armor-that-knelt-aftermath',
            continueLabel: "Receive the dead soldier's token",
          },
          failure: {
            outcome: "The old order rejects Jory's newer code and the suit rises with shieldless drill precision.",
            effects: [
              { type: 'vitals', resource: -2 },
              { type: 'flag', operation: 'add', flagId: 'kneeling-armor-fight-committed' },
            ],
            combatEncounterId: 'enc-ch01-kneeling-harness',
            nextSceneId: 'ch01-living-armor-that-knelt-aftermath',
            continueLabel: 'Put the levyman to rest',
          },
        },
      },
      {
        id: 'ch01-choice-armor-open-the-backplate',
        label: 'Open the harness from behind',
        detail: 'Use Cunning against difficulty 4 to find and release the hidden command strap.',
        exclusions: [{ type: 'flag', flagId: 'kneeling-armor-avoided' }],
        check: {
          stat: 'cunning',
          difficulty: 4,
          modifiers: [
            {
              label: 'Joints wedged +15',
              amount: 15,
              requirements: [{ type: 'flag', flagId: 'kneeling-armor-joints-wedged' }],
            },
          ],
          success: {
            outcome: 'You release the command strap without disturbing the corpse, and the armor collapses harmlessly around it.',
            effects: [
              { type: 'flag', operation: 'add', flagId: 'kneeling-armor-opened' },
              { type: 'flag', operation: 'add', flagId: 'kneeling-armor-peaceful' },
              { type: 'xp', amount: 20, source: 'quest' },
              { type: 'vitals', health: -1 },
            ],
            nextSceneId: 'ch01-living-armor-that-knelt-aftermath',
            continueLabel: 'Lay out the old service kit',
          },
          failure: {
            outcome: 'A hidden spring ejects the wedge and the dead soldier completes the interrupted sword draw.',
            effects: [
              { type: 'vitals', health: -4 },
              { type: 'flag', operation: 'add', flagId: 'kneeling-armor-fight-committed' },
            ],
            combatEncounterId: 'enc-ch01-kneeling-harness',
            nextSceneId: 'ch01-living-armor-that-knelt-aftermath',
            continueLabel: 'Survive the first draw',
          },
        },
      },
      {
        id: 'ch01-choice-armor-break-the-sword-arm',
        label: 'Break the sword arm before it rises',
        detail: 'Commit to battle and disable the rusted elbow before the occupied suit stands.',
        exclusions: [{ type: 'flag', flagId: 'kneeling-armor-avoided' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'kneeling-armor-fight-committed' },
          { type: 'combat', encounterId: 'enc-ch01-kneeling-harness' },
        ],
        outcome: 'The first blow snaps the rusted elbow lock, but the occupied suit stands and reaches for you with its free hand.',
        nextSceneId: 'ch01-living-armor-that-knelt-aftermath',
        continueLabel: 'Fight the occupied armor',
      },
      {
        id: 'ch01-choice-armor-pass-without-opening',
        label: 'Pass without opening the harness',
        detail: 'Keep every wagon beyond sword reach and leave the old order unresolved.',
        requirements: [{ type: 'flag', flagId: 'kneeling-armor-avoided' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'kneeling-armor-resolved' },
          { type: 'flag', operation: 'add', flagId: 'moving-armor-left-on-road' },
          { type: 'threat', amount: 1 },
        ],
        outcome: 'Through the narrow visor you glimpse leather holding a dead face upright, but the suit keeps its knee while the last wagon passes.',
        nextSceneId: 'ch01-main-the-first-arrow',
        continueLabel: 'Mark the hollow and regain the orchard road',
      },
    ],
  }),
  defineScene({
    ...COMMON,
    id: 'ch01-living-armor-that-knelt-aftermath',
    slot: 45,
    type: 'journey',
    journeySubtype: 'investigation',
    family: 'living-kneeling-armor-aftermath',
    pacing: 'quiet',
    illustrationId: 'scene-ch01-living-armor-that-knelt-aftermath',
    title: 'A Soldier Finally Unharnessed',
    requirements: [{ type: 'flag', flagId: 'kneeling-armor-route-chosen' }],
    exclusions: [{ type: 'flag', flagId: 'kneeling-armor-avoided' }],
    narrative: [
      "The old levy corpse lies flat at last. Its command token names the barrow road and bears a quartermaster's office number still used inside Greywatch. The useful pieces are a locking key, two sound plates, and the testimony of the token itself.",
    ],
    choices: [
      {
        id: 'ch01-choice-armor-take-the-harness-key',
        label: 'Take the harness key and record the burial',
        detail: 'Copy the command token, preserve the locking key, and give the soldier a proper cairn.',
        requirements: [{ type: 'flag', flagId: 'kneeling-armor-peaceful' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'kneeling-armor-resolved' },
          { type: 'item', operation: 'grant', itemId: 'charm-kneeling-harness-key', quantity: 1, destination: 'unbanked-loot' },
          { type: 'evidence', operation: 'add', evidenceId: 'old-levy-command-token' },
          { type: 'xp', amount: 8, source: 'quest' },
        ],
        outcome: 'Jory copies the office number before the guards build a proper cairn.',
        nextSceneId: 'ch01-main-the-first-arrow',
        continueLabel: 'Return to the orchard road',
      },
      {
        id: 'ch01-choice-armor-salvage-the-breastplate',
        label: 'Salvage one sound breastplate',
        detail: 'Keep one serviceable plate and leave the cloak and remaining harness with the dead levy.',
        requirements: [{ type: 'flag', flagId: 'kneeling-armor-fight-committed' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'kneeling-armor-resolved' },
          { type: 'item', operation: 'grant', itemId: 'armor-greywatch-guard-coat', quantity: 1, destination: 'unbanked-loot' },
          { type: 'gold', scope: 'unbanked', amount: 6 },
          { type: 'threat', amount: 1 },
        ],
        outcome: 'The plate is old but serviceable; the dead levy receives the cloak and the rest of the harness.',
        nextSceneId: 'ch01-main-the-first-arrow',
        continueLabel: 'Return to the orchard road',
      },
      {
        id: 'ch01-choice-armor-leave-the-hollow-marked',
        label: 'Mark the hollow and leave it alone',
        detail: 'Record the occupied armor so Greywatch can send a burial detail that knows its commands.',
        requirements: [{ type: 'flag', flagId: 'kneeling-armor-avoided' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'kneeling-armor-resolved' },
          { type: 'flag', operation: 'add', flagId: 'moving-armor-left-on-road' },
          { type: 'threat', amount: 1 },
        ],
        outcome: 'Jory marks the hollow on his route copy so Greywatch can send a burial detail that knows the old commands.',
        nextSceneId: 'ch01-main-the-first-arrow',
        continueLabel: 'Return to the orchard road',
      },
    ],
  }),
  defineScene({
    ...COMMON,
    id: 'ch01-living-war-camps-last-fire',
    slot: 52,
    type: 'journey',
    journeySubtype: 'moral-choice',
    family: 'living-abandoned-war-camp',
    weight: 4,
    pacing: 'quiet',
    illustrationId: 'scene-ch01-living-war-camps-last-fire',
    title: "The War Camp's Last Fire",
    narrative: [
      "The convoy skirts the abandoned edge of a goblin war camp. Most tents are gone, but one cook fire still burns beneath a rain hood. A wounded goblin quartermaster lies beside sacks marked with human family names, and a dead human officer's coded movement strip is pinned under his hand.",
    ],
    eligibility: { routes: ALL_ROUTES, minLevel: 1, maxLevel: 2 },
    requirements: [
      { type: 'flag', flagId: 'split-fletched-arrow-secured' },
      { type: 'flag', flagId: 'war-camp-route-chosen' },
    ],
    exclusions: [{ type: 'flag', flagId: 'war-camp-resolved' }],
    dialogue: [
      {
        speakerName: 'Quartermaster Vekk',
        text: 'Those are not trophies. We bought them back from your soldiers.',
        environmentIllustrationId: 'scene-ch01-living-war-camps-last-fire',
      },
      {
        speakerName: 'Jory Fen',
        text: 'The names are villages below Greywatch.',
        environmentIllustrationId: 'scene-ch01-living-war-camps-last-fire',
      },
    ],
    choices: [
      {
        id: 'ch01-choice-war-camp-treat-vekk',
        label: "Stop Vekk's bleeding",
        detail: 'Tear cloth from your field kit to keep the quartermaster conscious.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'war-camp-vekk-treated' },
          { type: 'flag', operation: 'add', flagId: 'war-camp-sensitive-custody' },
          { type: 'vitals', health: -1 },
        ],
        outcome: "Vekk stays conscious long enough to point at the officer's code.",
        nextSceneId: 'ch01-living-war-camps-last-fire-choice',
        continueLabel: 'Hear how the camp fell',
      },
      {
        id: 'ch01-choice-war-camp-secure-goods-first',
        label: 'Secure the family goods first',
        detail: 'Count the labeled sacks before deciding what the wounded quartermaster can tell you.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'war-camp-goods-secured' },
          { type: 'tension', amount: 1 },
        ],
        outcome: 'Guards count blankets, tools, and seed grain while Vekk weakens beside the fire.',
        nextSceneId: 'ch01-living-war-camps-last-fire-choice',
        continueLabel: 'Decide who receives the goods',
      },
      {
        id: 'ch01-choice-war-camp-search-the-perimeter',
        label: 'Search for whoever abandoned the fire',
        detail: 'Read the camp perimeter before entering the tent lanes.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'war-camp-perimeter-watched' },
          { type: 'threat', amount: -1 },
        ],
        outcome: 'You find warg tracks circling downwind and no marching goblin column.',
        nextSceneId: 'ch01-living-war-camps-last-fire-choice',
        continueLabel: 'Return before the scavengers close',
      },
    ],
  }),
  defineScene({
    ...COMMON,
    id: 'ch01-living-war-camps-last-fire-choice',
    slot: 53,
    type: 'combat',
    family: 'living-abandoned-war-camp-choice',
    pacing: 'danger',
    illustrationId: 'scene-ch01-living-war-camps-last-fire-choice',
    title: 'Goods Bought Twice',
    requirements: [{ type: 'flag', flagId: 'war-camp-route-chosen' }],
    narrative: [
      'Vekk says a human officer sold the goods to his camp, then returned with riders who slaughtered the buyers and planted goblin shields along Route Seven. Two hungry gloam wargs now creep between the empty tents, drawn by blood and the last fire.',
    ],
    choices: [
      {
        id: 'ch01-choice-war-camp-read-the-code',
        label: "Decode the officer's movement strip",
        detail: 'Use Cunning against difficulty 4 to read the supply code before the wargs close.',
        check: {
          stat: 'cunning',
          difficulty: 4,
          modifiers: [
            {
              label: 'Vekk conscious +10',
              amount: 10,
              requirements: [{ type: 'flag', flagId: 'war-camp-vekk-treated' }],
            },
          ],
          success: {
            outcome: 'Vekk supplies the missing supply abbreviations, linking the officer to six empty army carts.',
            effects: [
              { type: 'evidence', operation: 'add', evidenceId: 'war-camp-coded-order' },
              { type: 'flag', operation: 'add', flagId: 'war-camp-order-decoded' },
              { type: 'flag', operation: 'add', flagId: 'war-camp-sensitive-custody' },
              { type: 'xp', amount: 22, source: 'story' },
            ],
            nextSceneId: 'ch01-living-war-camps-last-fire-aftermath',
            continueLabel: 'Move Vekk and the goods',
          },
          failure: {
            outcome: 'The cipher consumes the moment in which the wargs could have been driven off.',
            effects: [
              { type: 'vitals', resource: -2 },
              { type: 'flag', operation: 'add', flagId: 'war-camp-fight-committed' },
            ],
            combatEncounterId: 'enc-ch01-war-camp-wargs',
            nextSceneId: 'ch01-living-war-camps-last-fire-aftermath',
            continueLabel: 'Defend the last fire',
          },
        },
      },
      {
        id: 'ch01-choice-war-camp-drive-off-wargs',
        label: 'Drive the wargs off without pursuing',
        detail: 'Use Will against difficulty 3 to make the scavengers believe the camp is defended.',
        check: {
          stat: 'will',
          difficulty: 3,
          modifiers: [
            {
              label: 'Perimeter watched +10',
              amount: 10,
              requirements: [{ type: 'flag', flagId: 'war-camp-perimeter-watched' }],
            },
          ],
          success: {
            outcome: 'Shields, fire, and a disciplined advance convince the scavengers that nothing here is abandoned.',
            effects: [
              { type: 'flag', operation: 'add', flagId: 'war-camp-wargs-driven-off' },
              { type: 'xp', amount: 16, source: 'quest' },
              { type: 'threat', amount: -1 },
            ],
            nextSceneId: 'ch01-living-war-camps-last-fire-aftermath',
            continueLabel: "Settle the camp's debts",
          },
          failure: {
            outcome: 'One warg breaks past the shield noise toward Vekk.',
            effects: [
              { type: 'vitals', health: -2 },
            ],
            combatEncounterId: 'enc-ch01-war-camp-wargs',
            nextSceneId: 'ch01-living-war-camps-last-fire-aftermath',
            continueLabel: 'Protect the wounded quartermaster',
          },
        },
      },
      {
        id: 'ch01-choice-war-camp-fight-for-the-sacks',
        label: 'Fight for Vekk and the sacks',
        detail: 'Hold the tent lane in battle while the guards move the wounded and the family goods.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'war-camp-fight-committed' },
          { type: 'combat', encounterId: 'enc-ch01-war-camp-wargs' },
        ],
        outcome: 'You close the tent lane while the guards drag Vekk and the family goods behind the cook stones.',
        nextSceneId: 'ch01-living-war-camps-last-fire-aftermath',
        continueLabel: 'Hold the last fire',
      },
    ],
  }),
  defineScene({
    ...COMMON,
    id: 'ch01-living-war-camps-last-fire-aftermath',
    slot: 54,
    type: 'journey',
    journeySubtype: 'moral-choice',
    family: 'living-abandoned-war-camp-aftermath',
    pacing: 'quiet',
    illustrationId: 'scene-ch01-living-war-camps-last-fire-aftermath',
    title: "The Quartermaster's Accounting",
    requirements: [{ type: 'flag', flagId: 'war-camp-route-chosen' }],
    narrative: [
      'The wargs are gone or dead. Vekk can travel hidden beneath wagon canvas, while the labeled goods can go to their families, to Greywatch stores, or back onto the courier road he served.',
    ],
    choices: [
      {
        id: 'ch01-choice-war-camp-return-family-goods',
        label: 'Carry the goods to their named families',
        detail: 'Spend four carried gold on transport and keep every sack outside the salvage ledger.',
        requirements: [{ type: 'gold', scope: 'unbanked', amount: 4 }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'war-camp-resolved' },
          { type: 'flag', operation: 'add', flagId: 'war-camp-family-goods-returned' },
          { type: 'faction', factionId: 'greywatch', amount: 2 },
          { type: 'gold', scope: 'unbanked', amount: -4 },
        ],
        outcome: 'Jory adds every sack to a witnessed return list and refuses to count it as convoy salvage.',
        nextSceneId: 'ch01-journey-the-field-surgery-road',
        continueLabel: 'Carry the wounded toward the bridge',
      },
      {
        id: 'ch01-choice-war-camp-hide-vekk-and-order',
        label: 'Hide Vekk and preserve the coded order',
        detail: 'Carry the wounded quartermaster and keep the order outside the public dispatch.',
        requirements: [{ type: 'flag', flagId: 'war-camp-sensitive-custody' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'war-camp-resolved' },
          { type: 'flag', operation: 'add', flagId: 'goblin-quartermaster-protected' },
          { type: 'evidence', operation: 'add', evidenceId: 'war-camp-coded-order' },
          { type: 'xp', amount: 10, source: 'quest' },
        ],
        outcome: 'Vekk rides under empty bandage canvas while Jory seals the order separately from the public dispatch.',
        nextSceneId: 'ch01-journey-the-field-surgery-road',
        continueLabel: 'Carry the wounded toward the bridge',
      },
      {
        id: 'ch01-choice-war-camp-turn-all-over',
        label: 'Turn survivor, goods, and order over at Greywatch',
        detail: "Declare the entire custody chain and leave Vekk's fate to the gate.",
        effects: [
          { type: 'flag', operation: 'add', flagId: 'war-camp-resolved' },
          { type: 'flag', operation: 'add', flagId: 'war-camp-custody-declared' },
          { type: 'faction', factionId: 'greywatch', amount: 1 },
          { type: 'tension', amount: 1 },
        ],
        outcome: "Jory writes a custody declaration that protects the goods from being claimed as ordinary loot but leaves Vekk's fate to the gate.",
        nextSceneId: 'ch01-journey-the-field-surgery-road',
        continueLabel: 'Carry the wounded toward the bridge',
      },
    ],
  }),
]);
