import { defineScene } from '../../builders';

const routes = ['kings-road', 'old-forest', 'ruined-pass'];
const base = (scene: any) => defineScene({ chapterId: 'ch01', region: 'gloamwood', weight: 100, eligibility: { routes, minLevel: 1, maxLevel: 2 }, requirements: [], exclusions: [], cooldownRuns: 0, oneShot: true, followUps: [], callbackPromises: [], dialogue: [{ speakerName: 'Mara', text: scene.line, environmentIllustrationId: scene.illustrationId }], ...scene });
const direct = (id: string, label: string, outcome: string, effects: any[], nextSceneId: string, continueLabel: string, extra = {}) => ({ id, label, detail: outcome, outcome, effects, nextSceneId, continueLabel, ...extra });
const checked = (id: string, label: string, stat: 'cunning' | 'will', difficulty: number, modifier: string, nextSceneId: string, continueLabel: string, effects: any[]) => ({ id, label, detail: `Attempt a ${stat} check.`, check: { stat, difficulty, modifiers: [{ label: modifier, amount: modifier.endsWith('+0') ? 0 : 5 }], success: { outcome: 'You establish what the road can prove.', effects, nextSceneId, continueLabel }, failure: { outcome: 'The rain leaves the reading uncertain.', effects, nextSceneId, continueLabel }, criticalSuccess: { outcome: 'You find a stronger record in the ground.', effects, nextSceneId, continueLabel }, criticalFailure: { outcome: 'The clearest mark is spoiled.', effects, nextSceneId, continueLabel } } });

export const CH01_LIVING_MARA = Object.freeze([
  base({ id: 'ch01-living-cut-milestone-setup', slot: 9, type: 'companion', family: 'mara-first-meeting', relationship: { kind: 'companion', companionId: 'mara' }, pacing: 'quiet', illustrationId: 'scene-ch01-living-cut-milestone-setup', title: 'A Scout Beside the Stone', line: 'Mara Vey, border scouts. Check the ruts before you trust either of us.', narrative: ['A lone woman waits by a cut milestone and keeps both hands clear of her bow.', 'Mara Vey names paired military tracks, a missing distance number, and birch bark tied low.'], choices: [
    direct('ch01-choice-name-yourself-to-mara', 'Give Mara your name', 'Mara repeats it once, then looks to the wagons.', [{ type: 'flag', operation: 'add', flagId: 'mara-met' }, { type: 'companion-loyalty', companionId: 'mara', amount: 2 }], 'ch01-living-cut-milestone-dialogue', "Hear Mara's evidence"),
    direct('ch01-choice-ask-for-her-patrol-order', 'Ask for her patrol order', 'She produces a rain-soft order signed before the tollhouse went silent.', [{ type: 'flag', operation: 'add', flagId: 'mara-met' }, { type: 'flag', operation: 'add', flagId: 'mara-order-seen' }], 'ch01-living-cut-milestone-dialogue', "Hear Mara's evidence"),
    direct('ch01-choice-keep-jory-between-you', 'Keep your distance', 'Mara accepts the caution without stepping closer.', [{ type: 'flag', operation: 'add', flagId: 'mara-met' }, { type: 'flag', operation: 'add', flagId: 'mara-met-warily' }, { type: 'companion-loyalty', companionId: 'mara', amount: -1 }], 'ch01-living-cut-milestone-dialogue', "Hear Mara's evidence"),
  ] }),
  base({ id: 'ch01-living-cut-milestone-dialogue', slot: 10, type: 'companion', family: 'mara-first-meeting', relationship: { kind: 'companion', companionId: 'mara' }, pacing: 'quiet', illustrationId: 'scene-ch01-living-cut-milestone-dialogue', title: 'Three Groups in the Rain', line: 'The third group walked south and wanted us to read north.', narrative: ['Mara lays a knotted cord across three rut sets and separates what she saw from what she inferred.'], choices: [
    checked('ch01-choice-test-maras-rut-count', 'Test the rut count', 'cunning', 6, 'Fresh chalk holds edges +5', 'ch01-living-cut-milestone-aftermath', 'Hear her route advice', [{ type: 'flag', operation: 'add', flagId: 'mara-claim-verified' }, { type: 'companion-loyalty', companionId: 'mara', amount: 4 }, { type: 'xp', amount: 10, source: 'story' }]),
    checked('ch01-choice-press-mara-for-one-certainty', 'Ask what she knows for certain', 'will', 6, 'Direct question +0', 'ch01-living-cut-milestone-aftermath', 'Hear her route advice', [{ type: 'flag', operation: 'add', flagId: 'mara-honesty-respected' }, { type: 'companion-loyalty', companionId: 'mara', amount: 3 }, { type: 'xp', amount: 10, source: 'story' }]),
    direct('ch01-choice-accept-maras-observation', 'Accept the observation', 'You accept the hidden direction without pretending it proves who made the tracks.', [{ type: 'flag', operation: 'add', flagId: 'mara-trusted-provisionally' }, { type: 'companion-loyalty', companionId: 'mara', amount: 2 }], 'ch01-living-cut-milestone-aftermath', 'Hear her route advice'),
  ] }),
  base({ id: 'ch01-living-cut-milestone-aftermath', slot: 10, type: 'companion', family: 'mara-first-meeting-aftermath', relationship: { kind: 'companion', companionId: 'mara' }, pacing: 'quiet', illustrationId: 'scene-ch01-living-cut-milestone-aftermath', title: 'The Warning She Can Prove', line: 'Follow, verify, or watch me from the road.', narrative: ['Mara does not ask to join the convoy. She offers one marked crossing, then continues her own patrol.'], choices: [
    direct('ch01-choice-thank-mara-without-a-promise', 'Thank her without a promise', 'Mara nods and walks ahead where the birches meet the road.', [{ type: 'flag', operation: 'add', flagId: 'mara-treated-as-scout' }, { type: 'companion-loyalty', companionId: 'mara', amount: 1 }], 'ch01-living-birch-marks-setup', 'Study the birch marks'),
    direct('ch01-choice-tell-mara-you-will-judge-the-path', 'Say you will judge the path', 'She answers that judgment is the work, not an insult.', [{ type: 'flag', operation: 'add', flagId: 'mara-path-to-be-tested' }, { type: 'companion-loyalty', companionId: 'mara', amount: 1 }], 'ch01-living-birch-marks-setup', 'Test the marked crossing'),
  ] }),
  base({ id: 'ch01-living-birch-marks-setup', slot: 10, type: 'journey', journeySubtype: 'investigation', family: 'birch-marks', pacing: 'quiet', illustrationId: 'scene-ch01-living-birch-marks-setup', title: 'Three Cuts on White Bark', line: 'High marks are mine. The low ones were added after dawn.', narrative: ['Fresh cuts repeat along a firm birch verge, while another mud-rubbed set hides lower on the trunks.'], choices: [
    direct('ch01-choice-copy-both-birch-marks', 'Copy both marks', 'Jory copies the high cuts and lower mud-dark cuts onto separate lines.', [{ type: 'flag', operation: 'add', flagId: 'both-birch-marks-copied' }, { type: 'evidence', operation: 'add', evidenceId: 'altered-birch-marks' }], 'ch01-living-birch-marks-choice', 'Choose which marks to follow'),
    direct('ch01-choice-keep-the-wagons-on-stone', 'Keep the wagons on stone', 'The drivers hold Route Seven while you examine the verge on foot.', [{ type: 'flag', operation: 'add', flagId: 'wagons-held-on-route-seven' }, { type: 'threat', amount: 1 }], 'ch01-living-birch-marks-choice', 'Choose which marks to follow'),
  ] }),
  base({ id: 'ch01-living-birch-marks-choice', slot: 10, type: 'journey', journeySubtype: 'investigation', family: 'birch-marks', pacing: 'quiet', illustrationId: 'scene-ch01-living-birch-marks-choice', title: 'Which Marks to Follow', line: 'My path gives up speed. The other gives up sight.', narrative: ['The high marks lead over dry roots. The false low marks turn into a hollow hidden from the milestone.'], choices: [
    direct('ch01-choice-accept-maras-high-marks', "Take Mara's marked path", 'The wagons use the firm verge and rejoin Route Seven below the tollhouse.', [{ type: 'flag', operation: 'add', flagId: 'mara-path-accepted' }, { type: 'companion-loyalty', companionId: 'mara', amount: 3 }, { type: 'threat', amount: -1 }, { type: 'tension', amount: 1 }], 'ch01-living-birch-marks-aftermath', 'Look down on the tollhouse'),
    checked('ch01-choice-verify-the-hidden-hollow', 'Verify the hidden hollow', 'cunning', 7, 'Both mark sets copied +5', 'ch01-living-birch-marks-aftermath', 'Look down on the tollhouse', [{ type: 'flag', operation: 'add', flagId: 'bell-wire-suspected' }, { type: 'flag', operation: 'add', flagId: 'birch-hollow-verified' }, { type: 'xp', amount: 10, source: 'story' }]),
    checked('ch01-choice-shadow-mara-through-birches', 'Shadow Mara instead of following openly', 'will', 7, 'Mara expects scrutiny +0', 'ch01-living-birch-marks-aftermath', 'Look down on the tollhouse', [{ type: 'flag', operation: 'add', flagId: 'mara-shadowed-cleanly' }, { type: 'flag', operation: 'add', flagId: 'bell-wire-suspected' }, { type: 'xp', amount: 10, source: 'story' }]),
  ] }),
  base({ id: 'ch01-living-birch-marks-aftermath', slot: 10, type: 'journey', journeySubtype: 'travel', family: 'birch-marks-aftermath', pacing: 'quiet', illustrationId: 'scene-ch01-living-birch-marks-aftermath', title: 'The Tollhouse Below', line: 'I will check the north ditch. Your wagons are your command.', narrative: ['The birches thin above an empty tollhouse. A narrow wire disappears under its eaves toward the orchard.'], choices: [
    direct('ch01-choice-approach-tollhouse-under-cover', 'Approach under the birches', 'The wagons stop below the rise while you reach the yard unseen.', [{ type: 'flag', operation: 'add', flagId: 'tollhouse-approach-hidden' }, { type: 'threat', amount: -1 }], 'ch01-main-the-empty-tollhouse', 'Enter the tollhouse yard'),
    direct('ch01-choice-bring-the-wagons-to-the-barrier', 'Bring the wagons to the barrier', 'The full convoy enters the yard together, ready to move but visible.', [{ type: 'flag', operation: 'add', flagId: 'tollhouse-convoy-close' }, { type: 'tension', amount: -1 }], 'ch01-main-the-empty-tollhouse', 'Call for the collector'),
  ] }),
]);
