import { defineScene } from '../../builders';

const ALL_ROUTES = ['kings-road', 'old-forest', 'ruined-pass'] as const;
const COMMON = {
  chapterId: 'ch01' as const,
  region: 'gloamwood' as const,
  weight: 100,
  eligibility: { routes: ALL_ROUTES, minLevel: 1, maxLevel: 2 },
  requirements: [],
  exclusions: [],
  cooldownRuns: 0,
  oneShot: true,
  followUps: [],
  callbackPromises: [],
};

export const CH01_LIVING_GREYWATCH_APPROACH = Object.freeze([
  defineScene({
    ...COMMON,
    id: 'ch01-living-millers-cart',
    slot: 23.1,
    type: 'journey',
    journeySubtype: 'side-quest',
    family: 'living-millers-cart',
    pacing: 'danger',
    illustrationId: 'scene-ch01-living-millers-cart',
    title: "The Miller's Cart",
    narrative: [
      "Below the watermill, the children's father is pinned between an overturned flour cart and the mill race wall. Two raiders are cutting the cart horse loose while smoke thickens above the bridge. The wagon convoy cannot turn on the narrow bank, but its repair rope can reach the axle.",
    ],
    eligibility: { routes: ['kings-road', 'old-forest'], minLevel: 1, maxLevel: 2 },
    requirements: [{ type: 'flag', flagId: 'orchard-volley-survived' }],
    exclusions: [{ type: 'flag', flagId: 'millers-cart-resolved' }],
    dialogue: [
      {
        speakerName: 'Miller Olan Firth',
        text: 'My children are in the upper room. Save them before you save flour.',
        environmentIllustrationId: 'scene-ch01-living-millers-cart',
      },
      {
        speakerName: 'Jory Fen',
        text: 'That cart can block the fire lane if we get it upright.',
        environmentIllustrationId: 'scene-ch01-living-millers-cart',
      },
    ],
    choices: [
      {
        id: 'ch01-choice-miller-rig-the-repair-rope',
        label: 'Rig the repair rope',
        detail: 'Spend one class resource and use the convoy rope to prepare a controlled lift.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'millers-cart-rope-ready' },
          { type: 'vitals', resource: -1 },
          { type: 'tension', amount: 1 },
        ],
        outcome: "The guards run the convoy's ordinary repair rope through the cart wheel while Olan shields his face from the rising water.",
        nextSceneId: 'ch01-living-millers-cart-rescue',
        continueLabel: 'Haul the cart clear',
      },
      {
        id: 'ch01-choice-miller-circle-the-raiders',
        label: 'Circle through the mill',
        detail: "Leave Jory at the bank and risk a watched approach through the mill's wet wheel room.",
        effects: [
          { type: 'flag', operation: 'add', flagId: 'millers-cart-flank-ready' },
          { type: 'threat', amount: 1 },
        ],
        outcome: "You leave Jory holding the bank and climb through the wet wheel room toward the raiders' backs.",
        nextSceneId: 'ch01-living-millers-cart-rescue',
        continueLabel: 'Reach the mill yard',
      },
      {
        id: 'ch01-choice-miller-leave-a-marker',
        label: 'Mark the family and keep moving',
        detail: 'Reduce immediate danger to the medicine convoy, but leave Olan beneath the trapped cart.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'millers-cart-abandoned' },
          { type: 'threat', amount: -1 },
        ],
        outcome: 'Jory ties a white strip to the mill door, but Olan and the trapped cart remain behind as the convoy begins turning toward the smoke.',
        nextSceneId: 'ch01-living-millers-cart-rescue',
        continueLabel: 'Pass the mill race',
      },
    ],
  }),
  defineScene({
    ...COMMON,
    id: 'ch01-living-millers-cart-rescue',
    slot: 23.11,
    type: 'combat',
    family: 'living-millers-cart-rescue',
    pacing: 'danger',
    illustrationId: 'scene-ch01-living-millers-cart-rescue',
    title: 'Axle in the Mill Race',
    narrative: [
      'As the convoy passes the mill race, the raiders kick the cart brake loose. Water takes the rear wheel, Olan slips lower against the wall, and one raider raises a horn toward the bridge. Anyone who stayed can still attempt force, a precise cut, or a fast fight. Anyone who ordered the convoy onward must now own that order.',
    ],
    choices: [
      {
        id: 'ch01-choice-miller-heave-the-axle',
        label: 'Heave the axle off Olan',
        detail: 'Use Strength against difficulty 3 to lift the loaded axle while Jory reaches Olan.',
        exclusions: [{ type: 'flag', flagId: 'millers-cart-abandoned' }],
        check: {
          stat: 'strength',
          difficulty: 3,
          modifiers: [
            {
              label: 'Repair rope secured +10',
              amount: 10,
              requirements: [{ type: 'flag', flagId: 'millers-cart-rope-ready' }],
            },
          ],
          success: {
            outcome: 'The axle rises long enough for Jory to drag Olan free and the raiders flee before the guards can close.',
            effects: [
              { type: 'flag', operation: 'add', flagId: 'miller-olan-rescued' },
              { type: 'flag', operation: 'add', flagId: 'miller-olan-available' },
              { type: 'flag', operation: 'add', flagId: 'millers-cart-recovered' },
              { type: 'xp', amount: 18, source: 'story' },
              { type: 'vitals', health: -1 },
            ],
            nextSceneId: 'ch01-living-millers-cart-aftermath',
            continueLabel: 'Bring Olan to his children',
          },
          failure: {
            outcome: 'The rope parts, the cart drops, and the raiders charge while the guards pull Olan clear by inches.',
            effects: [
              { type: 'vitals', health: -4 },
              { type: 'flag', operation: 'add', flagId: 'miller-olan-rescued-injured' },
              { type: 'flag', operation: 'add', flagId: 'miller-olan-available' },
              { type: 'flag', operation: 'add', flagId: 'millers-cart-destroyed' },
            ],
            combatEncounterId: 'enc-ch01-millers-cart-raiders',
            nextSceneId: 'ch01-living-millers-cart-aftermath',
            continueLabel: 'Defend the mill race',
          },
        },
      },
      {
        id: 'ch01-choice-miller-cut-the-trace-pin',
        label: 'Cut the trapped trace pin',
        detail: 'Use Cunning against difficulty 3 to free the horse and turn the cart against the bank.',
        exclusions: [{ type: 'flag', flagId: 'millers-cart-abandoned' }],
        check: {
          stat: 'cunning',
          difficulty: 3,
          modifiers: [
            {
              label: 'Flank from the mill +10',
              amount: 10,
              requirements: [{ type: 'flag', flagId: 'millers-cart-flank-ready' }],
            },
          ],
          success: {
            outcome: 'One exact cut frees the horse and rolls the cart against the bank, trapping the raiders on the wrong side.',
            effects: [
              { type: 'flag', operation: 'add', flagId: 'miller-olan-rescued' },
              { type: 'flag', operation: 'add', flagId: 'miller-olan-available' },
              { type: 'flag', operation: 'add', flagId: 'millers-cart-recovered' },
              { type: 'xp', amount: 20, source: 'story' },
              { type: 'vitals', resource: -1 },
            ],
            nextSceneId: 'ch01-living-millers-cart-aftermath',
            continueLabel: 'Use the cart at the bridge',
          },
          failure: {
            outcome: 'The pin snaps toward Olan, forcing you to catch it as the horn sounds.',
            effects: [
              { type: 'vitals', health: -3 },
              { type: 'threat', amount: 1 },
              { type: 'flag', operation: 'add', flagId: 'miller-olan-rescued-injured' },
              { type: 'flag', operation: 'add', flagId: 'miller-olan-available' },
            ],
            combatEncounterId: 'enc-ch01-millers-cart-raiders',
            nextSceneId: 'ch01-living-millers-cart-aftermath',
            continueLabel: 'Stop the horn bearer',
          },
        },
      },
      {
        id: 'ch01-choice-miller-rush-the-horn',
        label: 'Rush the horn bearer',
        detail: 'Leave the cart rescue to Jory and force an immediate battle before reinforcements answer.',
        exclusions: [{ type: 'flag', flagId: 'millers-cart-abandoned' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'miller-olan-rescued-injured' },
          { type: 'flag', operation: 'add', flagId: 'miller-olan-available' },
          { type: 'flag', operation: 'add', flagId: 'millers-cart-destroyed' },
          { type: 'combat', encounterId: 'enc-ch01-millers-cart-raiders' },
        ],
        outcome: 'You leave the cart to Jory and strike before the horn can call bridge reinforcements.',
        nextSceneId: 'ch01-living-millers-cart-aftermath',
        continueLabel: 'Fight beside the mill race',
      },
      {
        id: 'ch01-choice-miller-hold-the-order-to-leave',
        label: 'Hold to the order to leave',
        detail: 'Keep the medicine moving and accept the cost of leaving the miller family behind.',
        requirements: [{ type: 'flag', flagId: 'millers-cart-abandoned' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'miller-family-left-behind' },
          { type: 'tension', amount: 1 },
        ],
        outcome: 'The horn sounds behind the convoy while the mill race and Olan disappear around the bend.',
        nextSceneId: 'ch01-living-millers-cart-aftermath',
        continueLabel: 'Face what the choice cost',
      },
    ],
  }),
  defineScene({
    ...COMMON,
    id: 'ch01-living-millers-cart-aftermath',
    slot: 23.12,
    type: 'journey',
    journeySubtype: 'moral-choice',
    family: 'living-millers-cart-aftermath',
    pacing: 'quiet',
    illustrationId: 'scene-ch01-living-millers-cart-aftermath',
    title: 'Flour on the Bridge Wind',
    narrative: [
      'The convoy regroups beneath the mill. The bridge is close enough for sparks to land in the race, and every surviving person or cart will change what can be protected there.',
    ],
    choices: [
      {
        id: 'ch01-choice-miller-use-cart-as-bridge-cover',
        label: 'Roll the flour cart ahead as cover',
        detail: 'Turn the recovered cart into a moving shield for the burning bridge approach.',
        requirements: [{ type: 'flag', flagId: 'millers-cart-recovered' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'bridge-flour-cart-cover' },
          { type: 'flag', operation: 'add', flagId: 'millers-cart-resolved' },
          { type: 'xp', amount: 8, source: 'quest' },
        ],
        outcome: 'Olan empties the wet flour and helps lash the cart into a moving shield for the bridge approach.',
        nextSceneId: 'ch01-main-the-bridge-in-smoke',
        continueLabel: 'Approach the burning bridge',
      },
      {
        id: 'ch01-choice-miller-seat-olan-with-children',
        label: 'Seat Olan with his children',
        detail: 'Reunite the family inside the crowded medicine convoy before reaching the bridge.',
        requirements: [{ type: 'flag', flagId: 'miller-olan-available' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'miller-family-reunited' },
          { type: 'flag', operation: 'add', flagId: 'millers-cart-resolved' },
          { type: 'faction', factionId: 'greywatch', amount: 1 },
        ],
        outcome: 'The children make room among the bandage crates while Olan identifies the trapped families at the bridge.',
        nextSceneId: 'ch01-main-the-bridge-in-smoke',
        continueLabel: 'Approach the burning bridge',
      },
      {
        id: 'ch01-choice-miller-accept-the-empty-road',
        label: 'Accept the empty place behind you',
        detail: 'Continue with the medicine convoy and record the family left at the mill.',
        requirements: [{ type: 'flag', flagId: 'millers-cart-abandoned' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'miller-family-left-behind' },
          { type: 'flag', operation: 'add', flagId: 'millers-cart-resolved' },
          { type: 'tension', amount: 2 },
        ],
        outcome: 'No one speaks as the mill disappears behind smoke; the bridge now holds civilians who have no cart cover and no miller coming for them.',
        nextSceneId: 'ch01-main-the-bridge-in-smoke',
        continueLabel: 'Approach the burning bridge',
      },
    ],
  }),
  defineScene({
    ...COMMON,
    id: 'ch01-living-ash-on-officers-cuff',
    slot: 32.1,
    type: 'journey',
    journeySubtype: 'investigation',
    family: 'living-ash-evidence',
    pacing: 'quiet',
    illustrationId: 'scene-ch01-living-ash-on-officers-cuff',
    title: "Ash on the Officer's Cuff",
    narrative: [
      "The dead toll collector's clean uniform is staged, but a thumb-wide smear of grey ash remains inside his left cuff. Beside it, the dry orc banner carries the same sweet lamp-oil smell as the burned tollhouse. Rain is already stippling the exposed sleeve.",
    ],
    exclusions: [{ type: 'flag', flagId: 'ash-cuff-resolved' }],
    dialogue: [
      {
        speakerName: 'Jory Fen',
        text: 'A kiln burns pale. Tollhouse charcoal burns black. This is neither.',
        environmentIllustrationId: 'scene-ch01-living-ash-on-officers-cuff',
      },
      {
        speakerName: 'Mara Vey',
        text: 'Then prove where it came from before the rain decides for us.',
        environmentIllustrationId: 'scene-ch01-living-ash-on-officers-cuff',
      },
    ],
    choices: [
      {
        id: 'ch01-choice-ash-shelter-the-body',
        label: 'Shelter the body and tools',
        detail: 'Hold the convoy in exposed ground while guards protect the evidence from rain.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'ash-cuff-sheltered' },
          { type: 'threat', amount: 1 },
        ],
        outcome: 'Guards hold wagon canvas over the ditch while Jory lays out knife, wax, water, and sample papers.',
        nextSceneId: 'ch01-living-ash-on-officers-cuff-test',
        continueLabel: 'Test the ash',
      },
      {
        id: 'ch01-choice-ash-search-the-wheel-ruts',
        label: 'Search the nearby wheel ruts first',
        detail: 'Spend one class resource to compare the cuff residue with the freshest cart tracks.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'ash-cuff-ruts-compared' },
          { type: 'vitals', resource: -1 },
        ],
        outcome: 'You find the same ash pressed into a repaired army-cart tread before returning to the cuff.',
        nextSceneId: 'ch01-living-ash-on-officers-cuff-test',
        continueLabel: 'Compare the evidence',
      },
    ],
  }),
  defineScene({
    ...COMMON,
    id: 'ch01-living-ash-on-officers-cuff-test',
    slot: 32.11,
    type: 'journey',
    journeySubtype: 'investigation',
    family: 'living-ash-evidence-test',
    pacing: 'danger',
    illustrationId: 'scene-ch01-living-ash-on-officers-cuff-test',
    title: 'Three Ways to Test a Lie',
    narrative: [
      'The body, banner, arrow, and cart track tell one story only if their handling can be proved. The test must survive a skeptical gate captain, not merely satisfy the people standing in the ditch.',
    ],
    choices: [
      {
        id: 'ch01-choice-ash-lift-the-body-cloth',
        label: 'Lift the body without disturbing the ground',
        detail: 'Use Strength against difficulty 3 to expose the bank beneath the covered body.',
        check: {
          stat: 'strength',
          difficulty: 3,
          modifiers: [
            {
              label: 'Body sheltered +10',
              amount: 10,
              requirements: [{ type: 'flag', flagId: 'ash-cuff-sheltered' }],
            },
          ],
          success: {
            outcome: 'You expose a dry rectangle and army-cart splinters beneath the corpse, proving it was unloaded here.',
            effects: [
              { type: 'evidence', operation: 'add', evidenceId: 'officer-body-transported' },
              { type: 'flag', operation: 'add', flagId: 'ash-evidence-reliable' },
              { type: 'xp', amount: 18, source: 'story' },
            ],
            nextSceneId: 'ch01-living-ash-on-officers-cuff-aftermath',
            continueLabel: 'Record the transported body',
          },
          failure: {
            outcome: 'The wet bank gives way, smearing the ash and tracks together.',
            effects: [
              { type: 'vitals', health: -3 },
              { type: 'flag', operation: 'add', flagId: 'ash-evidence-partial' },
              { type: 'threat', amount: 1 },
            ],
            combatEncounterId: 'enc-ch01-recover-the-false-banner',
            nextSceneId: 'ch01-living-ash-on-officers-cuff-aftermath',
            continueLabel: 'Keep the raiders from the evidence',
          },
        },
      },
      {
        id: 'ch01-choice-ash-compare-burn-residue',
        label: 'Compare ash, oil, and cart tread',
        detail: 'Use Cunning against difficulty 3 to separate the cuff residue from the tollhouse fire.',
        check: {
          stat: 'cunning',
          difficulty: 3,
          modifiers: [
            {
              label: 'Rut comparison +10',
              amount: 10,
              requirements: [{ type: 'flag', flagId: 'ash-cuff-ruts-compared' }],
            },
          ],
          success: {
            outcome: 'The cuff ash matches residue embedded in the repaired military wheel and not the tollhouse fire.',
            effects: [
              { type: 'evidence', operation: 'add', evidenceId: 'army-cart-ash-match' },
              { type: 'flag', operation: 'add', flagId: 'ash-evidence-reliable' },
              { type: 'xp', amount: 20, source: 'story' },
            ],
            nextSceneId: 'ch01-living-ash-on-officers-cuff-aftermath',
            continueLabel: 'Seal the matched samples',
          },
          failure: {
            outcome: 'Rainwater makes the samples appear alike when their grain is not.',
            effects: [
              { type: 'flag', operation: 'add', flagId: 'ash-evidence-false-match' },
              { type: 'tension', amount: 2 },
            ],
            nextSceneId: 'ch01-living-ash-on-officers-cuff-aftermath',
            continueLabel: 'Carry the uncertain result',
          },
        },
      },
      {
        id: 'ch01-choice-ash-question-the-witnesses',
        label: 'Make the witnesses repeat the loading sequence',
        detail: 'Use Will against difficulty 4 to build one account from exhausted witnesses.',
        check: {
          stat: 'will',
          difficulty: 4,
          modifiers: [
            {
              label: 'Miller family reunited +10',
              amount: 10,
              requirements: [{ type: 'flag', flagId: 'miller-family-reunited' }],
            },
            {
              label: 'Mara supports the timeline +5',
              amount: 5,
              requirements: [{ type: 'flag', flagId: 'mara-met' }],
            },
          ],
          success: {
            outcome: 'Olan and the surviving toll officer independently place an army cart and sweet oil at the scene before dawn.',
            effects: [
              { type: 'evidence', operation: 'add', evidenceId: 'two-witness-loading-account' },
              { type: 'flag', operation: 'add', flagId: 'ash-evidence-reliable' },
              { type: 'xp', amount: 22, source: 'quest' },
            ],
            nextSceneId: 'ch01-living-ash-on-officers-cuff-aftermath',
            continueLabel: 'Write the joint account',
          },
          failure: {
            outcome: 'The exhausted witnesses contradict times and colors under pressure.',
            effects: [
              { type: 'flag', operation: 'add', flagId: 'ash-evidence-partial' },
              { type: 'faction', factionId: 'greywatch', amount: -1 },
              { type: 'tension', amount: 1 },
            ],
            nextSceneId: 'ch01-living-ash-on-officers-cuff-aftermath',
            continueLabel: 'Preserve what they agree on',
          },
        },
      },
    ],
  }),
  defineScene({
    ...COMMON,
    id: 'ch01-living-ash-on-officers-cuff-aftermath',
    slot: 32.12,
    type: 'journey',
    journeySubtype: 'investigation',
    family: 'living-ash-evidence-aftermath',
    pacing: 'quiet',
    illustrationId: 'scene-ch01-living-ash-on-officers-cuff-aftermath',
    title: 'Evidence Wrapped Against Rain',
    narrative: [
      'Jory has room for one formal conclusion on the dispatch wrapper. Whatever he writes will decide whether Greywatch receives proof, suspicion, or a confident mistake.',
    ],
    choices: [
      {
        id: 'ch01-choice-ash-file-reliable-chain',
        label: 'File the full chain of evidence',
        detail: 'Send Greywatch every defensible link without naming a culprit the evidence has not proved.',
        requirements: [{ type: 'flag', flagId: 'ash-evidence-reliable' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'ash-cuff-resolved' },
          { type: 'flag', operation: 'add', flagId: 'greywatch-evidence-reliable' },
          { type: 'xp', amount: 10, source: 'story' },
          { type: 'faction', factionId: 'greywatch', amount: 1 },
        ],
        outcome: 'Jory lists body transport, ash source, witnesses, and custody marks without naming an unproved culprit.',
        nextSceneId: 'ch01-living-riders-in-valley',
        continueLabel: 'Take the evidence toward Greywatch',
      },
      {
        id: 'ch01-choice-ash-file-limited-finding',
        label: 'File only what can still be defended',
        detail: 'Report the staged banner while leaving damaged parts of the evidence chain unconfirmed.',
        requirements: [{ type: 'flag', flagId: 'ash-evidence-partial' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'ash-cuff-resolved' },
          { type: 'flag', operation: 'add', flagId: 'greywatch-evidence-partial' },
          { type: 'threat', amount: -1 },
        ],
        outcome: 'The report calls the banner staged but leaves the transport method and attackers unconfirmed.',
        nextSceneId: 'ch01-living-riders-in-valley',
        continueLabel: 'Take the evidence toward Greywatch',
      },
      {
        id: 'ch01-choice-ash-mark-the-match-uncertain',
        label: 'Mark the ash match as uncertain',
        detail: 'Keep the contaminated sample but prevent it from becoming a false accusation.',
        requirements: [{ type: 'flag', flagId: 'ash-evidence-false-match' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'ash-cuff-resolved' },
          { type: 'flag', operation: 'add', flagId: 'greywatch-evidence-contaminated' },
          { type: 'tension', amount: 1 },
          { type: 'evidence', operation: 'remove', evidenceId: 'army-cart-ash-match' },
        ],
        outcome: 'Jory encloses the sample but writes that rain may have contaminated it, preventing a false certainty from becoming an accusation.',
        nextSceneId: 'ch01-living-riders-in-valley',
        continueLabel: 'Take the evidence toward Greywatch',
      },
    ],
  }),
  defineScene({
    ...COMMON,
    id: 'ch01-living-riders-in-valley',
    slot: 36.1,
    type: 'journey',
    journeySubtype: 'travel',
    family: 'living-valley-pursuit',
    pacing: 'danger',
    threatChange: 1,
    illustrationId: 'scene-ch01-living-riders-in-valley',
    title: 'Riders in the Valley',
    narrative: [
      "Six mounted figures enter the valley behind the convoy, using the same short horn signal heard at the tollhouse. Greywatch's lanterns are visible above, but the damaged wagons cannot outrun fresh cavalry on the open climb. A sheep track, a stone toll arch, and the official road offer three different risks.",
    ],
    exclusions: [{ type: 'flag', flagId: 'riders-valley-resolved' }],
    dialogue: [
      {
        speakerName: 'Rider Captain',
        text: 'Leave the dispatch tube in the road and take your medicine to the gate.',
        environmentIllustrationId: 'scene-ch01-living-riders-in-valley',
      },
      {
        speakerName: 'Jory Fen',
        text: 'They know the tube, not just the cargo.',
        environmentIllustrationId: 'scene-ch01-living-riders-in-valley',
      },
    ],
    choices: [
      {
        id: 'ch01-choice-riders-hide-sheep-track',
        label: 'Turn onto the screened sheep track',
        detail: 'Take the damaged wagons between high gorse banks and risk the narrow hidden ground.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'riders-hide-prepared' },
          { type: 'tension', amount: 1 },
        ],
        outcome: 'Drivers wrap the harness bells and guide the wagons between high gorse banks.',
        nextSceneId: 'ch01-living-riders-in-valley-crossing',
        continueLabel: 'Break their line of sight',
      },
      {
        id: 'ch01-choice-riders-answer-under-arch',
        label: 'Answer from beneath the toll arch',
        detail: 'Spend one class resource and force the riders to approach through a narrow stone opening.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'riders-bargain-prepared' },
          { type: 'vitals', resource: -1 },
        ],
        outcome: 'You halt under stone where only two horses can approach together and call for terms.',
        nextSceneId: 'ch01-living-riders-in-valley-crossing',
        continueLabel: 'Buy time with terms',
      },
      {
        id: 'ch01-choice-riders-form-roadblock',
        label: 'Form a roadblock around the wagons',
        detail: 'Set the surviving wagons axle to axle and prepare the guards for a direct attack.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'riders-fight-prepared' },
          { type: 'tension', amount: -1 },
        ],
        outcome: 'The wagons turn axle to axle while the guards ground pikes in the gap.',
        nextSceneId: 'ch01-living-riders-in-valley-crossing',
        continueLabel: 'Hold the valley road',
      },
    ],
  }),
  defineScene({
    ...COMMON,
    id: 'ch01-living-riders-in-valley-crossing',
    slot: 36.11,
    type: 'combat',
    family: 'living-valley-pursuit-crossing',
    pacing: 'danger',
    illustrationId: 'scene-ch01-living-riders-in-valley-crossing',
    title: 'The Distance to Greywatch',
    narrative: [
      'The riders divide, two climbing for a view of the sheep track and four advancing on the road. Their captain wants Jory and the dispatch alive. The convoy needs one clean opening to reach the final hill.',
    ],
    choices: [
      {
        id: 'ch01-choice-riders-hide-the-wagons',
        label: 'Hide wagons and false the trail',
        detail: 'Use Cunning against difficulty 4 to send the mounted scouts into the wrong gully.',
        requirements: [{ type: 'flag', flagId: 'riders-hide-prepared' }],
        check: {
          stat: 'cunning',
          difficulty: 4,
          modifiers: [
            {
              label: 'Pursuit line broken +10',
              amount: 10,
              requirements: [{ type: 'flag', flagId: 'pursuit-line-broken' }],
            },
            {
              label: 'Mara reads the ridge +5',
              amount: 5,
              requirements: [{ type: 'flag', flagId: 'mara-met' }],
            },
          ],
          success: {
            outcome: 'Empty sacks and one loose horse draw the scouts along the wrong gully.',
            effects: [
              { type: 'flag', operation: 'add', flagId: 'riders-valley-evaded' },
              { type: 'xp', amount: 20, source: 'story' },
              { type: 'threat', amount: -2 },
            ],
            nextSceneId: 'ch01-living-riders-in-valley-aftermath',
            continueLabel: 'Rejoin the Greywatch climb',
          },
          failure: {
            outcome: 'A wheel cuts fresh chalk through the disguise and the riders turn at once.',
            effects: [
              { type: 'flag', operation: 'add', flagId: 'riders-valley-fought' },
              { type: 'vitals', health: -2 },
            ],
            combatEncounterId: 'enc-ch01-reedbank-pursuers',
            nextSceneId: 'ch01-living-riders-in-valley-aftermath',
            continueLabel: 'Defend the hidden wagons',
          },
        },
      },
      {
        id: 'ch01-choice-riders-bargain-for-ten-minutes',
        label: 'Trade the false banner for ten minutes',
        detail: 'Use Will against difficulty 4 to prove the evidence is already beyond their full control.',
        requirements: [{ type: 'flag', flagId: 'riders-bargain-prepared' }],
        check: {
          stat: 'will',
          difficulty: 4,
          modifiers: [
            {
              label: 'Reliable staged evidence +10',
              amount: 10,
              requirements: [{ type: 'flag', flagId: 'greywatch-evidence-reliable' }],
            },
          ],
          success: {
            outcome: 'You show that copies of the evidence are already separated, and the captain accepts the dry banner rather than risk witnesses reaching the gate.',
            effects: [
              { type: 'flag', operation: 'remove', flagId: 'orc-banner-recovered' },
              { type: 'flag', operation: 'add', flagId: 'false-banner-surrendered' },
              { type: 'flag', operation: 'add', flagId: 'riders-valley-delayed' },
              { type: 'xp', amount: 18, source: 'story' },
              { type: 'tension', amount: -1 },
            ],
            nextSceneId: 'ch01-living-riders-in-valley-aftermath',
            continueLabel: 'Use the time you bought',
          },
          failure: {
            outcome: 'The captain sees that Jory still guards the useful proof and orders a charge.',
            effects: [
              { type: 'vitals', resource: -2 },
              { type: 'flag', operation: 'add', flagId: 'riders-valley-fought' },
            ],
            combatEncounterId: 'enc-ch01-reedbank-pursuers',
            nextSceneId: 'ch01-living-riders-in-valley-aftermath',
            continueLabel: 'Fight beneath the arch',
          },
        },
      },
      {
        id: 'ch01-choice-riders-break-the-captains-line',
        label: "Break the captain's line",
        detail: 'Use the prepared pike gap to force the riders into an immediate battle.',
        requirements: [{ type: 'flag', flagId: 'riders-fight-prepared' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'riders-valley-fought' },
          { type: 'combat', encounterId: 'enc-ch01-reedbank-pursuers' },
        ],
        outcome: 'The guard pikes force the first horses inward where the riders cannot circle.',
        nextSceneId: 'ch01-living-riders-in-valley-aftermath',
        continueLabel: 'Drive off the pursuit',
      },
      {
        id: 'ch01-choice-riders-scatter-caltrops',
        label: 'Scatter a caltrop pouch and withdraw',
        detail: 'Consume one caltrop pouch to close the road without fighting the mounted pursuit.',
        requirements: [{ type: 'item', itemId: 'consumable-caltrop-pouch', quantity: 1, scope: 'pack' }],
        effects: [
          { type: 'item', operation: 'remove', itemId: 'consumable-caltrop-pouch', quantity: 1 },
          { type: 'flag', operation: 'add', flagId: 'riders-valley-evaded' },
          { type: 'xp', amount: 12, source: 'quest' },
          { type: 'threat', amount: -2 },
        ],
        outcome: 'The riders rein in before the iron points while the wagons climb beyond bow range.',
        nextSceneId: 'ch01-living-riders-in-valley-aftermath',
        continueLabel: 'Climb while the road is closed',
      },
    ],
  }),
  defineScene({
    ...COMMON,
    id: 'ch01-living-riders-in-valley-aftermath',
    slot: 36.12,
    type: 'journey',
    journeySubtype: 'travel',
    family: 'living-valley-pursuit-aftermath',
    pacing: 'quiet',
    illustrationId: 'scene-ch01-living-riders-in-valley-aftermath',
    title: 'Greywatch Above the Pines',
    narrative: [
      "The valley falls behind and Greywatch's wall finally remains in sight. The convoy's speed, wounds, and pursuers will determine what reaches the gate with it.",
    ],
    choices: [
      {
        id: 'ch01-choice-riders-keep-the-hidden-pace',
        label: 'Keep the hidden pace',
        detail: 'Use the clean escape to arrange the witnesses before hailing the gate.',
        requirements: [{ type: 'flag', flagId: 'riders-valley-evaded' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'riders-valley-resolved' },
          { type: 'flag', operation: 'add', flagId: 'greywatch-arrival-quiet' },
          { type: 'item', operation: 'grant', itemId: 'consumable-caltrop-pouch', quantity: 1, destination: 'pack' },
          { type: 'xp', amount: 8, source: 'quest' },
        ],
        outcome: 'The convoy reaches the final hill unseen, with enough room to arrange witnesses before hailing the gate.',
        nextSceneId: 'ch01-main-before-the-gates-close',
        continueLabel: 'Approach Greywatch quietly',
      },
      {
        id: 'ch01-choice-riders-spend-the-bought-time',
        label: 'Spend the bought time on the wounded',
        detail: 'Use the delay to stabilize the convoy before the bargain expires.',
        requirements: [{ type: 'flag', flagId: 'riders-valley-delayed' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'riders-valley-resolved' },
          { type: 'flag', operation: 'add', flagId: 'greywatch-arrival-ordered' },
          { type: 'vitals', health: 3 },
          { type: 'threat', amount: -1 },
        ],
        outcome: 'Jory checks every bandage and evidence packet before the riders begin moving again.',
        nextSceneId: 'ch01-main-before-the-gates-close',
        continueLabel: 'Reach the gate before the bargain ends',
      },
      {
        id: 'ch01-choice-riders-carry-the-battle-to-the-gate',
        label: 'Carry the battle warning uphill',
        detail: 'Reach Greywatch visibly pursued and make the sentries prepare for a fight.',
        requirements: [{ type: 'flag', flagId: 'riders-valley-fought' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'riders-valley-resolved' },
          { type: 'flag', operation: 'add', flagId: 'greywatch-arrival-pursued' },
          { type: 'faction', factionId: 'greywatch', amount: 1 },
          { type: 'tension', amount: 1 },
        ],
        outcome: "The wounded riders withdraw, but Greywatch's sentries can see armed movement behind your wagons.",
        nextSceneId: 'ch01-main-before-the-gates-close',
        continueLabel: 'Call a pursuit warning to the gate',
      },
    ],
  }),
]);
