import { defineScene } from '../../builders';

const ALL_ROUTES = ['kings-road', 'old-forest', 'ruined-pass'] as const;
const COMMON = {
  chapterId: 'ch01' as const,
  region: 'gloamwood' as const,
  weight: 100,
  eligibility: { routes: ALL_ROUTES, minLevel: 1, maxLevel: 2 },
  requirements: [],
  exclusions: [],
  cooldownRuns: 0,
  oneShot: true,
  followUps: [],
  callbackPromises: [],
};

export const CH01_LIVING_SWORD_AND_WARD = Object.freeze([
  defineScene({
    ...COMMON,
    id: 'ch01-living-sword-in-barrow-clay',
    slot: 31.1,
    type: 'journey',
    journeySubtype: 'investigation',
    family: 'living-barrow-sword',
    weight: 3,
    pacing: 'quiet',
    illustrationId: 'scene-ch01-living-sword-in-barrow-clay',
    title: 'The Sword in Barrow Clay',
    narrative: [
      'A black-hilted sword stands point-down in a roadside burial mound, driven through a flat stone carved with a levy name. Rain beads on a clean edge while every other iron fitting nearby has rusted. A copper strip around the grip reads: "Grave-Tithe, drawn only to finish the named dead."',
    ],
    requirements: [{ type: 'flag', flagId: 'bridge-crossed' }],
    exclusions: [{ type: 'flag', flagId: 'barrow-sword-resolved' }],
    dialogue: [
      {
        speakerName: 'Jory Fen',
        text: 'That is a warning with a price attached.',
        environmentIllustrationId: 'scene-ch01-living-sword-in-barrow-clay',
      },
      {
        speakerName: 'Voice Beneath the Clay',
        text: 'Dismiss me or draw.',
        environmentIllustrationId: 'scene-ch01-living-sword-in-barrow-clay',
      },
    ],
    choices: [
      {
        id: 'ch01-choice-barrow-read-the-burial-name',
        label: 'Read the levy record and leave the blade',
        detail: 'Identify the named soldier before touching the clean sword or its copper strip.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'barrow-sword-name-read' },
          { type: 'tension', amount: -1 },
        ],
        outcome: 'The stone names Halren Vale, a levy sergeant never formally released from the old barrow-road watch.',
        nextSceneId: 'ch01-living-sword-in-barrow-clay-binding',
        continueLabel: 'Answer the named dead',
      },
      {
        id: 'ch01-choice-barrow-clear-the-binding-strip',
        label: 'Clear clay from the copper binding',
        detail: 'Spend one class resource to expose the old dismissal phrase without drawing the blade.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'barrow-sword-binding-exposed' },
          { type: 'vitals', resource: -1 },
        ],
        outcome: 'Careful scraping reveals a dismissal phrase beneath the visible warning.',
        nextSceneId: 'ch01-living-sword-in-barrow-clay-binding',
        continueLabel: 'Attempt a safe unbinding',
      },
      {
        id: 'ch01-choice-barrow-take-the-sword-now',
        label: 'Pull Grave-Tithe free now',
        detail: 'Claim the weapon immediately and accept that its intact binding may follow you.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'grave-tithe-taken-cursed' },
          { type: 'item', operation: 'grant', itemId: 'weapon-grave-tithe', quantity: 1, destination: 'unbanked-loot' },
        ],
        outcome: 'The sword comes free easily, and an armored hand breaks through the clay around your boot.',
        nextSceneId: 'ch01-living-sword-in-barrow-clay-binding',
        continueLabel: 'Face the barrow warden',
      },
    ],
  }),
  defineScene({
    ...COMMON,
    id: 'ch01-living-sword-in-barrow-clay-binding',
    slot: 31.11,
    type: 'combat',
    family: 'living-barrow-sword-binding',
    pacing: 'danger',
    illustrationId: 'scene-ch01-living-sword-in-barrow-clay-binding',
    title: 'The Practical Price of Grave-Tithe',
    narrative: [
      'The copper strip explains the curse plainly. Whoever carries Grave-Tithe loses blood whenever they refuse a named challenge, and the blade cannot be sold or discarded until Halren Vale is dismissed by name. A dead levy hand shifts beneath the mound as the road falls quiet.',
    ],
    choices: [
      {
        id: 'ch01-choice-barrow-dismiss-halren',
        label: "Speak Halren's full dismissal",
        detail: 'Use Will against difficulty 4 to release Halren from the named watch before lifting the sword.',
        exclusions: [{ type: 'flag', flagId: 'grave-tithe-taken-cursed' }],
        check: {
          stat: 'will',
          difficulty: 4,
          modifiers: [
            {
              label: 'Burial name read +10',
              amount: 10,
              requirements: [{ type: 'flag', flagId: 'barrow-sword-name-read' }],
            },
            {
              label: 'Binding exposed +5',
              amount: 5,
              requirements: [{ type: 'flag', flagId: 'barrow-sword-binding-exposed' }],
            },
          ],
          success: {
            outcome: 'The hand relaxes and the copper strip splits, leaving the valuable blade unbound.',
            effects: [
              { type: 'flag', operation: 'add', flagId: 'grave-tithe-safely-unbound' },
              { type: 'item', operation: 'grant', itemId: 'weapon-grave-tithe', quantity: 1, destination: 'unbanked-loot' },
              { type: 'xp', amount: 24, source: 'story' },
            ],
            nextSceneId: 'ch01-living-sword-in-barrow-clay-aftermath',
            continueLabel: 'Lift the unbound sword',
          },
          failure: {
            outcome: 'One title is wrong, and Halren rises to demand trial by arms.',
            effects: [
              { type: 'vitals', resource: -2 },
              { type: 'flag', operation: 'add', flagId: 'grave-tithe-fight-committed' },
            ],
            combatEncounterId: 'enc-ch01-grave-tithe-warden',
            nextSceneId: 'ch01-living-sword-in-barrow-clay-aftermath',
            continueLabel: "Answer Halren's challenge",
          },
        },
      },
      {
        id: 'ch01-choice-barrow-cut-the-copper-strip',
        label: 'Cut the binding without drawing the blade',
        detail: 'Use Cunning against difficulty 5 to sever the repair seam without disturbing the grave.',
        exclusions: [{ type: 'flag', flagId: 'grave-tithe-taken-cursed' }],
        check: {
          stat: 'cunning',
          difficulty: 5,
          modifiers: [
            {
              label: 'Binding exposed +15',
              amount: 15,
              requirements: [{ type: 'flag', flagId: 'barrow-sword-binding-exposed' }],
            },
          ],
          success: {
            outcome: 'The strip parts at its repair seam and the curse remains with the grave, not the sword.',
            effects: [
              { type: 'flag', operation: 'add', flagId: 'grave-tithe-safely-unbound' },
              { type: 'item', operation: 'grant', itemId: 'weapon-grave-tithe', quantity: 1, destination: 'unbanked-loot' },
              { type: 'xp', amount: 22, source: 'quest' },
              { type: 'vitals', health: -1 },
            ],
            nextSceneId: 'ch01-living-sword-in-barrow-clay-aftermath',
            continueLabel: 'Wrap the safe blade',
          },
          failure: {
            outcome: 'The strip coils around your wrist and the warden wakes.',
            effects: [
              { type: 'vitals', health: -4 },
              { type: 'flag', operation: 'add', flagId: 'grave-tithe-taken-cursed' },
              { type: 'item', operation: 'grant', itemId: 'weapon-grave-tithe', quantity: 1, destination: 'unbanked-loot' },
            ],
            combatEncounterId: 'enc-ch01-grave-tithe-warden',
            nextSceneId: 'ch01-living-sword-in-barrow-clay-aftermath',
            continueLabel: 'Fight while bound to the blade',
          },
        },
      },
      {
        id: 'ch01-choice-barrow-reseat-the-sword',
        label: 'Reseat the sword and seal the clay',
        detail: 'Restore the binding exactly and leave the named watch undisturbed.',
        exclusions: [{ type: 'flag', flagId: 'grave-tithe-taken-cursed' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'grave-tithe-left-bound' },
          { type: 'threat', amount: -1 },
        ],
        outcome: 'The hand sinks back as you press the flat stone and copper strip into their original positions.',
        nextSceneId: 'ch01-living-sword-in-barrow-clay-aftermath',
        continueLabel: "Leave Halren's watch intact",
      },
      {
        id: 'ch01-choice-barrow-hold-the-drawn-blade',
        label: 'Hold the drawn blade against Halren',
        detail: 'Accept the named challenge and fight with the cursed sword already in hand.',
        requirements: [{ type: 'flag', flagId: 'grave-tithe-taken-cursed' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'grave-tithe-fight-committed' },
          { type: 'combat', encounterId: 'enc-ch01-grave-tithe-warden' },
        ],
        outcome: 'The copper strip bites into the grip while Halren rises to test the person who drew his sword.',
        nextSceneId: 'ch01-living-sword-in-barrow-clay-aftermath',
        continueLabel: 'Answer the named challenge',
      },
    ],
  }),
  defineScene({
    ...COMMON,
    id: 'ch01-living-sword-in-barrow-clay-aftermath',
    slot: 31.12,
    type: 'journey',
    journeySubtype: 'moral-choice',
    family: 'living-barrow-sword-aftermath',
    pacing: 'quiet',
    illustrationId: 'scene-ch01-living-sword-in-barrow-clay-aftermath',
    title: 'A Blade With a Named Debt',
    narrative: [
      'Grave-Tithe is either wrapped in the wagon, bound to its carrier, or standing again above Halren Vale. The convoy must record the choice before it reaches the staged body ahead.',
    ],
    choices: [
      {
        id: 'ch01-choice-barrow-carry-the-unbound-blade',
        label: 'Carry the unbound Grave-Tithe',
        detail: 'Record the safely dismissed blade as lawful convoy custody.',
        requirements: [{ type: 'flag', flagId: 'grave-tithe-safely-unbound' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'barrow-sword-resolved' },
          { type: 'flag', operation: 'add', flagId: 'grave-tithe-lawfully-carried' },
          { type: 'xp', amount: 8, source: 'quest' },
        ],
        outcome: 'The blade stays cold and silent when the wagon moves.',
        nextSceneId: 'ch01-main-a-banner-placed-too-neatly',
        continueLabel: 'Continue to the staged body',
      },
      {
        id: 'ch01-choice-barrow-accept-the-blood-price',
        label: 'Carry Grave-Tithe under its blood price',
        detail: "Keep the cursed weapon until a Greywatch smith can complete Halren's dismissal.",
        requirements: [{ type: 'flag', flagId: 'grave-tithe-taken-cursed' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'barrow-sword-resolved' },
          { type: 'flag', operation: 'add', flagId: 'grave-tithe-bound' },
        ],
        outcome: "The strip tightens once around the grip. Until a Greywatch smith completes Halren's dismissal, declining any explicitly named combat challenge costs 2 Health; accepting it suppresses that cost.",
        nextSceneId: 'ch01-main-a-banner-placed-too-neatly',
        continueLabel: 'Continue to the staged body',
      },
      {
        id: 'ch01-choice-barrow-claim-after-trial',
        label: "Claim Grave-Tithe after Halren's trial",
        detail: 'Carry the blade won in trial while preserving its intact binding for the Greywatch smith.',
        requirements: [{ type: 'flag', flagId: 'grave-tithe-fight-committed' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'barrow-sword-resolved' },
          { type: 'flag', operation: 'add', flagId: 'grave-tithe-bound' },
          { type: 'item', operation: 'grant', itemId: 'weapon-grave-tithe', quantity: 1, destination: 'unbanked-loot' },
        ],
        outcome: 'Halren is still, but the intact copper strip binds the blade to the victor until Greywatch completes the dismissal.',
        nextSceneId: 'ch01-main-a-banner-placed-too-neatly',
        continueLabel: 'Continue to the staged body',
      },
      {
        id: 'ch01-choice-barrow-mark-the-grave-for-greywatch',
        label: 'Mark the grave for a burial detail',
        detail: "Leave Grave-Tithe in place and carry only Halren's service record to Greywatch.",
        requirements: [{ type: 'flag', flagId: 'grave-tithe-left-bound' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'barrow-sword-resolved' },
          { type: 'evidence', operation: 'add', evidenceId: 'halren-vale-burial-record' },
          { type: 'faction', factionId: 'greywatch', amount: 1 },
        ],
        outcome: 'Jory copies the name and leaves the blade exactly where the old levy placed it.',
        nextSceneId: 'ch01-main-a-banner-placed-too-neatly',
        continueLabel: 'Continue to the staged body',
      },
    ],
  }),
  defineScene({
    ...COMMON,
    id: 'ch01-living-ward-beneath-shrine',
    slot: 32.2,
    type: 'journey',
    journeySubtype: 'investigation',
    family: 'living-failing-shrine-ward',
    weight: 2,
    pacing: 'quiet',
    illustrationId: 'scene-ch01-living-ward-beneath-shrine',
    title: 'The Ward Beneath the Shrine',
    narrative: [
      "A roadside saint shrine has collapsed into a root cellar. Four iron ward nails still pin a chalk ring around a trapped gloam warg below, but one nail lifts with every breath the animal takes. The creature is scarred by an officer's chain collar and frightened, not speaking or shapeless.",
    ],
    requirements: [{ type: 'flag', flagId: 'greywatch-evidence-reliable' }],
    exclusions: [{ type: 'flag', flagId: 'shrine-ward-resolved' }],
    dialogue: [
      {
        speakerName: 'Jory Fen',
        text: 'That collar has the same cart-office stamp as the ash evidence.',
        environmentIllustrationId: 'scene-ch01-living-ward-beneath-shrine',
      },
      {
        speakerName: 'Mara Vey',
        text: 'Repair the ring or clear the road. Do not stand over it arguing.',
        environmentIllustrationId: 'scene-ch01-living-ward-beneath-shrine',
      },
    ],
    choices: [
      {
        id: 'ch01-choice-shrine-brace-the-failing-nail',
        label: 'Brace the lifting ward nail',
        detail: 'Spend one class resource to hold the failing nail with a wagon pin.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'shrine-ward-braced' },
          { type: 'vitals', resource: -1 },
        ],
        outcome: 'A wagon pin holds the iron head down for a few more minutes.',
        nextSceneId: 'ch01-living-ward-beneath-shrine-choice',
        continueLabel: "Decide the creature's fate",
      },
      {
        id: 'ch01-choice-shrine-clear-a-release-lane',
        label: 'Clear a release lane away from the road',
        detail: 'Spend health moving broken stone so the frightened warg has a safe route away.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'shrine-release-lane' },
          { type: 'vitals', health: -1 },
        ],
        outcome: 'Guards drag broken stone aside, opening a gully that leads away from wagons and farms.',
        nextSceneId: 'ch01-living-ward-beneath-shrine-choice',
        continueLabel: 'Open or repair the ward',
      },
      {
        id: 'ch01-choice-shrine-raise-weapons',
        label: 'Prepare to kill it if the nail lifts',
        detail: 'Close shields around the cellar lip and prepare for a direct fight.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'shrine-kill-line-ready' },
          { type: 'tension', amount: 1 },
        ],
        outcome: 'Shields close around the cellar lip while the collar chain scrapes below.',
        nextSceneId: 'ch01-living-ward-beneath-shrine-choice',
        continueLabel: 'Hold the failing ring',
      },
    ],
  }),
  defineScene({
    ...COMMON,
    id: 'ch01-living-ward-beneath-shrine-choice',
    slot: 32.21,
    type: 'combat',
    family: 'living-failing-shrine-ward-choice',
    pacing: 'danger',
    illustrationId: 'scene-ch01-living-ward-beneath-shrine-choice',
    title: 'Four Nails and One Breath',
    narrative: [
      'The ward is an ordinary binding pattern powered by tension between its four iron nails. Repairing it preserves the prison. Breaking one safe segment can release the collared warg into the cleared gully. A careless break frees it toward the medicine team.',
    ],
    choices: [
      {
        id: 'ch01-choice-shrine-repair-the-ring',
        label: 'Reset all four ward nails',
        detail: 'Use Will against difficulty 4 to restore the whole binding without opening the road side.',
        check: {
          stat: 'will',
          difficulty: 4,
          modifiers: [
            {
              label: 'Failing nail braced +10',
              amount: 10,
              requirements: [{ type: 'flag', flagId: 'shrine-ward-braced' }],
            },
          ],
          success: {
            outcome: 'The chalk flares once and settles as the warg lies down, contained until Greywatch can remove the collar.',
            effects: [
              { type: 'flag', operation: 'add', flagId: 'shrine-ward-repaired' },
              { type: 'xp', amount: 24, source: 'story' },
              { type: 'vitals', resource: -1 },
            ],
            nextSceneId: 'ch01-living-ward-beneath-shrine-aftermath',
            continueLabel: 'Take the stamped collar record',
          },
          failure: {
            outcome: 'The lifting nail tears free and the ring opens toward the road.',
            effects: [
              { type: 'vitals', resource: -3, health: -2 },
              { type: 'flag', operation: 'add', flagId: 'shrine-kill-fight-committed' },
            ],
            combatEncounterId: 'enc-ch01-shrine-warg',
            nextSceneId: 'ch01-living-ward-beneath-shrine-aftermath',
            continueLabel: 'Keep the creature from the wagons',
          },
        },
      },
      {
        id: 'ch01-choice-shrine-open-the-gully-segment',
        label: 'Break only the gully segment',
        detail: 'Use Cunning against difficulty 4 to open one safe gap toward the cleared gully.',
        check: {
          stat: 'cunning',
          difficulty: 4,
          modifiers: [
            {
              label: 'Release lane cleared +15',
              amount: 15,
              requirements: [{ type: 'flag', flagId: 'shrine-release-lane' }],
            },
          ],
          success: {
            outcome: 'The warg bolts through the safe gap and disappears uphill, leaving its broken officer collar behind.',
            effects: [
              { type: 'flag', operation: 'add', flagId: 'shrine-creature-released-away' },
              { type: 'evidence', operation: 'add', evidenceId: 'officer-beast-collar' },
              { type: 'xp', amount: 20, source: 'quest' },
              { type: 'threat', amount: -1 },
            ],
            nextSceneId: 'ch01-living-ward-beneath-shrine-aftermath',
            continueLabel: 'Recover the broken collar',
          },
          failure: {
            outcome: 'The chalk breaks on both sides and the panicked animal lunges at the nearest movement.',
            effects: [
              { type: 'vitals', health: -3 },
              { type: 'flag', operation: 'add', flagId: 'shrine-kill-fight-committed' },
            ],
            combatEncounterId: 'enc-ch01-shrine-warg',
            nextSceneId: 'ch01-living-ward-beneath-shrine-aftermath',
            continueLabel: 'Survive the failed release',
          },
        },
      },
      {
        id: 'ch01-choice-shrine-break-the-ward-and-strike',
        label: 'Break the ward into the kill line',
        detail: 'Release the warg directly into the prepared shields and commit to battle.',
        requirements: [{ type: 'flag', flagId: 'shrine-kill-line-ready' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'shrine-kill-fight-committed' },
          { type: 'combat', encounterId: 'enc-ch01-shrine-warg' },
        ],
        outcome: 'The last nail comes free toward the waiting shields, and the collared beast charges the only opening.',
        nextSceneId: 'ch01-living-ward-beneath-shrine-aftermath',
        continueLabel: 'Fight at the cellar lip',
      },
    ],
  }),
  defineScene({
    ...COMMON,
    id: 'ch01-living-ward-beneath-shrine-aftermath',
    slot: 32.22,
    type: 'journey',
    journeySubtype: 'moral-choice',
    family: 'living-failing-shrine-ward-aftermath',
    pacing: 'quiet',
    illustrationId: 'scene-ch01-living-ward-beneath-shrine-aftermath',
    title: 'What the Ward Was Holding',
    narrative: [
      'The shrine is quiet. The officer-stamped collar proves someone transported the warg beside the same cart chain traced by the ash. One sound ward nail remains useful, but taking it weakens any repair left behind.',
    ],
    choices: [
      {
        id: 'ch01-choice-shrine-leave-the-repaired-ward',
        label: 'Leave all four nails and mark the shrine',
        detail: 'Preserve the living evidence and give Greywatch a safe recovery location.',
        requirements: [{ type: 'flag', flagId: 'shrine-ward-repaired' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'shrine-ward-resolved' },
          { type: 'flag', operation: 'add', flagId: 'shrine-ward-stable' },
          { type: 'evidence', operation: 'add', evidenceId: 'officer-beast-collar' },
          { type: 'xp', amount: 8, source: 'quest' },
        ],
        outcome: 'Jory sketches the collar stamp while the stable ring holds for a Greywatch animal detail.',
        nextSceneId: 'ch01-living-riders-in-valley',
        continueLabel: 'Return to the Greywatch road',
      },
      {
        id: 'ch01-choice-shrine-take-the-loose-nail-released',
        label: 'Take the loose ward nail',
        detail: 'Preserve the broken collar and carry one cold iron nail after the animal escapes.',
        requirements: [{ type: 'flag', flagId: 'shrine-creature-released-away' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'shrine-ward-resolved' },
          { type: 'item', operation: 'grant', itemId: 'charm-shrine-ward-nail', quantity: 1, destination: 'unbanked-loot' },
          { type: 'evidence', operation: 'add', evidenceId: 'officer-beast-collar' },
        ],
        outcome: "The cold iron nail goes into clean cloth while the broken collar goes into Jory's evidence case.",
        nextSceneId: 'ch01-living-riders-in-valley',
        continueLabel: 'Return to the Greywatch road',
      },
      {
        id: 'ch01-choice-shrine-take-the-loose-nail-fought',
        label: 'Take the loose ward nail',
        detail: 'Preserve the broken collar and carry one cold iron nail after the fight.',
        requirements: [{ type: 'flag', flagId: 'shrine-kill-fight-committed' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'shrine-ward-resolved' },
          { type: 'item', operation: 'grant', itemId: 'charm-shrine-ward-nail', quantity: 1, destination: 'unbanked-loot' },
          { type: 'evidence', operation: 'add', evidenceId: 'officer-beast-collar' },
        ],
        outcome: "The cold iron nail goes into clean cloth while the broken collar goes into Jory's evidence case.",
        nextSceneId: 'ch01-living-riders-in-valley',
        continueLabel: 'Return to the Greywatch road',
      },
      {
        id: 'ch01-choice-shrine-bury-collar-with-creature',
        label: 'Bury the collar with the creature',
        detail: "Leave the physical collar in the grave and keep only Jory's witnessed sketch.",
        requirements: [{ type: 'flag', flagId: 'shrine-kill-fight-committed' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'shrine-ward-resolved' },
          { type: 'flag', operation: 'add', flagId: 'shrine-creature-buried' },
          { type: 'tension', amount: -1 },
        ],
        outcome: "The collar remains proof you chose not to take, recorded only in Jory's witnessed sketch.",
        nextSceneId: 'ch01-living-riders-in-valley',
        continueLabel: 'Return to the Greywatch road',
      },
    ],
  }),
  defineScene({
    ...COMMON,
    id: 'ch01-living-teeth-under-siege-cart',
    slot: 40.1,
    type: 'journey',
    journeySubtype: 'travel',
    family: 'living-siege-cart-maw',
    weight: 2,
    pacing: 'danger',
    illustrationId: 'scene-ch01-living-teeth-under-siege-cart',
    title: 'Teeth Under the Siege Cart',
    narrative: [
      "A ruined siege cart blocks the quarry cutting below Greywatch. Something broad and low has made a den under its iron belly, feeding on dead draft horses and collecting every chain it can drag beneath the frame. It shows a pale row of teeth when the medicine wagon's axle squeals, but it does not charge while food remains between you.",
    ],
    requirements: [{ type: 'flag', flagId: 'riders-valley-resolved' }],
    exclusions: [{ type: 'flag', flagId: 'siege-cart-maw-resolved' }],
    dialogue: [
      {
        speakerName: 'Jory Fen',
        text: 'It wants the axle noise or the horse smell.',
        environmentIllustrationId: 'scene-ch01-living-teeth-under-siege-cart',
      },
      {
        speakerName: 'Mara Vey',
        text: 'Then give it a different sound, a different meal, or a wall it cannot dig through.',
        environmentIllustrationId: 'scene-ch01-living-teeth-under-siege-cart',
      },
    ],
    choices: [
      {
        id: 'ch01-choice-cart-maw-set-a-meat-drag',
        label: 'Rig a food drag away from the road',
        detail: 'Spend three carried gold on caravan rations and lead the creature toward the empty quarry.',
        requirements: [{ type: 'gold', scope: 'unbanked', amount: 3 }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'cart-maw-distraction-ready' },
          { type: 'gold', scope: 'unbanked', amount: -3 },
        ],
        outcome: 'Guards tie salted meat to a loose wheel rim and run the line toward the empty quarry.',
        nextSceneId: 'ch01-living-teeth-under-siege-cart-crossing',
        continueLabel: 'Draw the monster from its den',
      },
      {
        id: 'ch01-choice-cart-maw-set-the-counterweight',
        label: 'Turn the siege counterweight into a trap',
        detail: 'Free one rotten support and brace the hanging stone above the chain nest.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'cart-maw-trap-ready' },
          { type: 'vitals', health: -1 },
        ],
        outcome: 'You free one rotten support and brace the hanging stone above the chain nest.',
        nextSceneId: 'ch01-living-teeth-under-siege-cart-crossing',
        continueLabel: 'Lure it beneath the weight',
      },
      {
        id: 'ch01-choice-cart-maw-offer-the-broken-chain',
        label: 'Offer a bright broken chain and wait',
        detail: 'Spend one class resource to hold the team still while the creature studies the metal.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'cart-maw-bargain-ready' },
          { type: 'vitals', resource: -1 },
        ],
        outcome: 'The creature stops chewing and reaches one careful claw toward the chain, interested in metal more than flesh.',
        nextSceneId: 'ch01-living-teeth-under-siege-cart-crossing',
        continueLabel: 'Bargain for the road',
      },
      {
        id: 'ch01-choice-cart-maw-draw-weapons',
        label: 'Drive it out by force',
        detail: 'Strike the cart frame and draw the Cart-Maw away from the medicine wagons.',
        effects: [{ type: 'flag', operation: 'add', flagId: 'cart-maw-fight-ready' }],
        outcome: 'The guards strike the cart frame until the creature moves behind its shield of chained timber.',
        nextSceneId: 'ch01-living-teeth-under-siege-cart-crossing',
        continueLabel: 'Draw the Cart-Maw into the open',
      },
    ],
  }),
  defineScene({
    ...COMMON,
    id: 'ch01-living-teeth-under-siege-cart-crossing',
    slot: 40.11,
    type: 'combat',
    family: 'living-siege-cart-maw-crossing',
    pacing: 'danger',
    illustrationId: 'scene-ch01-living-teeth-under-siege-cart-crossing',
    title: 'The Chain Nest',
    narrative: [
      "The Cart-Maw is an animal made dangerous by the siege wreck: hide thickened by old burns, teeth worn on harness buckles, and a nest that turns chains into armor. It can be led away, pinned beneath the counterweight, traded a harmless piece of iron, or fought.",
    ],
    choices: [
      {
        id: 'ch01-choice-cart-maw-draw-it-to-quarry',
        label: 'Draw it after the food drag',
        detail: 'Use Cunning against difficulty 4 to make the bait sound like a moving axle.',
        requirements: [{ type: 'flag', flagId: 'cart-maw-distraction-ready' }],
        check: {
          stat: 'cunning',
          difficulty: 4,
          success: {
            outcome: 'The rim rattles like a moving axle and leads the creature deep into the quarry while the convoy passes.',
            effects: [
              { type: 'flag', operation: 'add', flagId: 'cart-maw-distracted' },
              { type: 'flag', operation: 'add', flagId: 'cart-maw-left-alive' },
              { type: 'xp', amount: 20, source: 'story' },
              { type: 'threat', amount: -2 },
            ],
            nextSceneId: 'ch01-living-teeth-under-siege-cart-aftermath',
            continueLabel: 'Search the abandoned chain nest',
          },
          failure: {
            outcome: 'The line catches under the wagon and snaps the bait back toward the horses.',
            effects: [
              { type: 'vitals', health: -2 },
              { type: 'threat', amount: 1 },
              { type: 'flag', operation: 'add', flagId: 'cart-maw-fight-committed' },
            ],
            combatEncounterId: 'enc-ch01-siege-cart-maw',
            nextSceneId: 'ch01-living-teeth-under-siege-cart-aftermath',
            continueLabel: 'Protect the horse team',
          },
        },
      },
      {
        id: 'ch01-choice-cart-maw-drop-the-counterweight',
        label: 'Drop the counterweight behind it',
        detail: 'Use Strength against difficulty 4 to pin the den without crushing the animal.',
        requirements: [{ type: 'flag', flagId: 'cart-maw-trap-ready' }],
        check: {
          stat: 'strength',
          difficulty: 4,
          success: {
            outcome: 'The stone falls between monster and den, trapping it unharmed in the quarry while the road opens.',
            effects: [
              { type: 'flag', operation: 'add', flagId: 'cart-maw-trapped' },
              { type: 'flag', operation: 'add', flagId: 'cart-maw-left-alive' },
              { type: 'flag', operation: 'add', flagId: 'cart-maw-tonic-access' },
              { type: 'xp', amount: 22, source: 'quest' },
              { type: 'vitals', health: -1 },
            ],
            nextSceneId: 'ch01-living-teeth-under-siege-cart-aftermath',
            continueLabel: 'Clear the siege cart',
          },
          failure: {
            outcome: 'The rotten lever breaks, dropping chain across your shoulder as the creature charges.',
            effects: [
              { type: 'vitals', health: -5 },
              { type: 'flag', operation: 'add', flagId: 'cart-maw-fight-committed' },
              { type: 'flag', operation: 'add', flagId: 'cart-maw-tonic-access' },
            ],
            combatEncounterId: 'enc-ch01-siege-cart-maw',
            nextSceneId: 'ch01-living-teeth-under-siege-cart-aftermath',
            continueLabel: 'Fight clear of the fallen chains',
          },
        },
      },
      {
        id: 'ch01-choice-cart-maw-trade-chain-for-passage',
        label: 'Roll the bright chain beyond the den',
        detail: 'Use Will against difficulty 3 to hold the convoy still until the creature accepts the trade.',
        requirements: [{ type: 'flag', flagId: 'cart-maw-bargain-ready' }],
        check: {
          stat: 'will',
          difficulty: 3,
          modifiers: [
            {
              label: 'Quiet arrival +5',
              amount: 5,
              requirements: [{ type: 'flag', flagId: 'greywatch-arrival-quiet' }],
            },
          ],
          success: {
            outcome: 'The creature drags the chain under the cart and watches without attacking while both wagons pass.',
            effects: [
              { type: 'flag', operation: 'add', flagId: 'cart-maw-bargained-past' },
              { type: 'flag', operation: 'add', flagId: 'cart-maw-left-alive' },
              { type: 'xp', amount: 18, source: 'story' },
              { type: 'tension', amount: -1 },
            ],
            nextSceneId: 'ch01-living-teeth-under-siege-cart-aftermath',
            continueLabel: 'Pass without breaking the bargain',
          },
          failure: {
            outcome: 'A guard moves too soon, and the Cart-Maw treats the rolling wheel as a rival taking its prize.',
            effects: [
              { type: 'vitals', resource: -2 },
              { type: 'flag', operation: 'add', flagId: 'cart-maw-fight-committed' },
            ],
            combatEncounterId: 'enc-ch01-siege-cart-maw',
            nextSceneId: 'ch01-living-teeth-under-siege-cart-aftermath',
            continueLabel: 'Keep it away from the axle',
          },
        },
      },
      {
        id: 'ch01-choice-cart-maw-finish-the-fight',
        label: 'Hold it beyond the wagon line',
        detail: 'Draw the creature into open ground where the chained timbers cannot reach the wagons.',
        requirements: [{ type: 'flag', flagId: 'cart-maw-fight-ready' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'cart-maw-fight-committed' },
          { type: 'flag', operation: 'add', flagId: 'cart-maw-tonic-access' },
          { type: 'combat', encounterId: 'enc-ch01-siege-cart-maw' },
        ],
        outcome: 'You draw the creature into open ground where its chain armor cannot catch the wagon wheels.',
        nextSceneId: 'ch01-living-teeth-under-siege-cart-aftermath',
        continueLabel: 'Defeat the Cart-Maw',
      },
    ],
  }),
  defineScene({
    ...COMMON,
    id: 'ch01-living-teeth-under-siege-cart-aftermath',
    slot: 40.12,
    type: 'journey',
    journeySubtype: 'moral-choice',
    family: 'living-siege-cart-maw-aftermath',
    pacing: 'quiet',
    illustrationId: 'scene-ch01-living-teeth-under-siege-cart-aftermath',
    title: 'What the Siege Left Behind',
    narrative: [
      "The road is open. Beneath the cart lies a Greywatch siege-chain maker's plate, a smooth shed tooth, and a sealed tonic box dragged from an older wreck. Taking a trophy, salvaging supplies, or leaving the den intact each tells a different story at the gate.",
    ],
    choices: [
      {
        id: 'ch01-choice-cart-maw-take-the-shed-tooth',
        label: 'Take only the shed tooth',
        detail: 'Recover the old tooth without entering the living animal\'s occupied den.',
        requirements: [{ type: 'flag', flagId: 'cart-maw-left-alive' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'siege-cart-maw-resolved' },
          { type: 'item', operation: 'grant', itemId: 'charm-cart-maw-tooth', quantity: 1, destination: 'unbanked-loot' },
          { type: 'evidence', operation: 'add', evidenceId: 'greywatch-siege-chain-plate' },
          { type: 'xp', amount: 8, source: 'quest' },
        ],
        outcome: 'The old tooth comes from the dirt without entering the occupied den, and Jory wraps the maker plate separately.',
        nextSceneId: 'ch01-main-before-the-gates-close',
        continueLabel: 'Climb to Greywatch',
      },
      {
        id: 'ch01-choice-cart-maw-salvage-tonics',
        label: 'Salvage the sealed tonic box',
        detail: 'Take the intact medicine box from the opened chain nest.',
        requirements: [{ type: 'flag', flagId: 'cart-maw-tonic-access' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'siege-cart-maw-resolved' },
          { type: 'item', operation: 'grant', itemId: 'consumable-greywatch-tonic', quantity: 2, destination: 'unbanked-loot' },
          { type: 'gold', scope: 'unbanked', amount: 5 },
          { type: 'threat', amount: 1 },
        ],
        outcome: 'The seal is old but sound, and the two bottles inside remain clear.',
        nextSceneId: 'ch01-main-before-the-gates-close',
        continueLabel: 'Climb to Greywatch',
      },
      {
        id: 'ch01-choice-cart-maw-leave-the-den-intact',
        label: 'Leave the den and mark a safe boundary',
        detail: 'Mark the distance at which the living Cart-Maw kept its bargain.',
        requirements: [{ type: 'flag', flagId: 'cart-maw-left-alive' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'siege-cart-maw-resolved' },
          { type: 'flag', operation: 'add', flagId: 'cart-maw-den-marked' },
          { type: 'faction', factionId: 'greywatch', amount: 1 },
        ],
        outcome: 'White stones mark the distance at which the creature held its bargain, giving later wagons a usable warning.',
        nextSceneId: 'ch01-main-before-the-gates-close',
        continueLabel: 'Climb to Greywatch',
      },
      {
        id: 'ch01-choice-cart-maw-take-the-jaw-plate',
        label: 'Take the hardened jaw plate',
        detail: 'Salvage one useful armor plate and leave the rest of the animal beneath the cart.',
        requirements: [{ type: 'flag', flagId: 'cart-maw-fight-committed' }],
        effects: [
          { type: 'flag', operation: 'add', flagId: 'siege-cart-maw-resolved' },
          { type: 'item', operation: 'grant', itemId: 'armor-cart-maw-jawguard', quantity: 1, destination: 'unbanked-loot' },
          { type: 'threat', amount: -1 },
        ],
        outcome: 'The useful plate comes free from the burned outer hide; the rest of the animal remains beneath the cart.',
        nextSceneId: 'ch01-main-before-the-gates-close',
        continueLabel: 'Climb to Greywatch',
      },
    ],
  }),
]);
