import { defineScene } from '../../builders';
const routes = ['kings-road', 'old-forest', 'ruined-pass'];
const base = (scene: any) => defineScene({ chapterId: 'ch01', region: 'gloamwood', weight: 100, eligibility: { routes, minLevel: 1, maxLevel: 2 }, requirements: [], exclusions: [], cooldownRuns: 0, oneShot: true, followUps: [], callbackPromises: [], dialogue: [{ speakerName: 'Jory', text: scene.line, environmentIllustrationId: scene.illustrationId }], ...scene });
const direct = (id: string, label: string, outcome: string, effects: any[], nextSceneId: string, continueLabel: string, extra = {}) => ({ id, label, detail: outcome, outcome, effects, nextSceneId, continueLabel, ...extra });
const checked = (id: string, label: string, stat: 'strength' | 'cunning' | 'will', difficulty: number, modifier: string, nextSceneId: string, continueLabel: string, effects: any[], combatEncounterId?: string, extra = {}) => ({ id, label, detail: `Attempt a ${stat} check.`, ...extra, check: { stat, difficulty, modifiers: [{ label: modifier, amount: modifier.endsWith('+10') ? 10 : 5 }], success: { outcome: 'You deny the attackers their prepared advantage.', effects, nextSceneId, continueLabel }, failure: { outcome: 'The danger is contained, but it leaves a cost.', effects, nextSceneId, continueLabel }, criticalSuccess: { outcome: 'You retain proof while breaking the attack.', effects, nextSceneId, continueLabel }, criticalFailure: { outcome: 'The attackers use the mistake to close.', effects, nextSceneId, continueLabel, ...(combatEncounterId ? { combatEncounterId } : {}) } } });

export const CH01_LIVING_AMBUSH = Object.freeze([
  base({ id: 'ch01-living-smoke-verge-setup', slot: 15, type: 'journey', journeySubtype: 'travel', family: 'smoke-beyond-verge', pacing: 'danger', illustrationId: 'scene-ch01-living-smoke-verge-setup', title: 'A Thin Column North', line: 'There was no smoke when we left the kiln.', narrative: ['A narrow grey column rises beyond the verge while charcoal-burner Ressa Holt approaches with her family.'], choices: [
    direct('ch01-choice-warn-the-charcoal-burners', 'Warn the travelers', 'Ressa turns the mule cart into the lee of the bank.', [{ type: 'flag', operation: 'add', flagId: 'verge-travelers-warned' }, { type: 'faction', factionId: 'greywatch', amount: 1 }], 'ch01-living-smoke-verge-choice', 'Reach the signal fire'),
    direct('ch01-choice-scout-the-smoke-alone', 'Scout alone', 'You leave the convoy under Jory’s hand and reach the hedgerow alone.', [{ type: 'flag', operation: 'add', flagId: 'verge-scouted-alone' }, { type: 'threat', amount: -1 }, { type: 'vitals', resource: -1 }], 'ch01-living-smoke-verge-choice', 'Reach the signal fire'),
    direct('ch01-choice-form-around-the-convoy', 'Protect the convoy', 'Drivers bring the wagon poles together as travelers shelter inside.', [{ type: 'flag', operation: 'add', flagId: 'verge-convoy-formed' }, { type: 'tension', amount: 1 }], 'ch01-living-smoke-verge-choice', 'Reach the signal fire'),
  ] }),
  base({ id: 'ch01-living-smoke-verge-choice', slot: 16, type: 'journey', journeySubtype: 'investigation', family: 'smoke-beyond-verge', pacing: 'danger', illustrationId: 'scene-ch01-living-smoke-verge-choice', title: 'The Signal Fire', line: 'Back to the wagons. This is patrol work.', narrative: ['Damp grass burns inside a pierced clay pot while a false patrol watcher and goblin guard the escape path.'], choices: [
    checked('ch01-choice-smother-the-signal-between-puffs', 'Smother the signal between puffs', 'cunning', 7, 'Pierced pot shows the cadence +5', 'ch01-living-smoke-verge-aftermath', 'Regroup at the verge', [{ type: 'flag', operation: 'add', flagId: 'verge-signal-stopped' }, { type: 'flag', operation: 'add', flagId: 'opening-volley-delayed' }, { type: 'xp', amount: 10, source: 'story' }, { type: 'threat', amount: -1 }], 'enc-ch01-verge-signalers'),
    checked('ch01-choice-order-the-watcher-to-stand-down', 'Order the watcher to stand down', 'will', 7, 'No patrol badge visible +5', 'ch01-living-smoke-verge-aftermath', 'Regroup at the verge', [{ type: 'flag', operation: 'add', flagId: 'verge-watcher-detained' }, { type: 'evidence', operation: 'add', evidenceId: 'false-patrol-signal' }, { type: 'xp', amount: 10, source: 'story' }], 'enc-ch01-verge-signalers'),
    direct('ch01-choice-attack-the-signal-team', 'Attack before they run', 'You cross the hedge before the watcher can complete another hand sign.', [{ type: 'flag', operation: 'add', flagId: 'verge-signal-team-engaged' }, { type: 'combat', encounterId: 'enc-ch01-verge-signalers' }], 'ch01-living-smoke-verge-aftermath', 'Take the signal pot'),
  ] }),
  base({ id: 'ch01-living-smoke-verge-aftermath', slot: 16, type: 'journey', journeySubtype: 'travel', family: 'smoke-beyond-verge-aftermath', pacing: 'quiet', illustrationId: 'scene-ch01-living-smoke-verge-aftermath', title: 'The Orchard Has Been Warned', line: 'The dispatch names our route. The smoke names our cargo.', narrative: ['The road runs between low orchard walls. Someone prepared this ground for the medicine wagons.'], choices: [
    direct('ch01-choice-send-the-travelers-south', 'Send the travelers south under cover', 'Ressa’s cart disappears behind the bank before the convoy enters the orchard.', [{ type: 'flag', operation: 'add', flagId: 'verge-travelers-safe' }, { type: 'faction', factionId: 'greywatch', amount: 1 }, { type: 'xp', amount: 8, source: 'quest' }], 'ch01-main-the-first-arrow', 'Enter the orchard road'),
    direct('ch01-choice-keep-the-travelers-inside-the-wagons', 'Keep everyone together', 'The travelers crouch between medicine cases while guards take corners.', [{ type: 'flag', operation: 'add', flagId: 'verge-group-kept-together' }, { type: 'tension', amount: -1 }, { type: 'threat', amount: 1 }], 'ch01-main-the-first-arrow', 'Advance in formation'),
  ] }),
  base({ id: 'ch01-living-split-fletched-arrow-setup', slot: 18, type: 'journey', journeySubtype: 'investigation', family: 'split-fletched-arrow', pacing: 'danger', illustrationId: 'scene-ch01-living-split-fletched-arrow-setup', title: 'Black, White, and Fresh Glue', line: 'Royal shaft. New feathers. Someone wanted us to recognize the wrong owner.', narrative: ['The arrow pinning Jory’s dispatch has old military wood and new black-and-white feathers.'], choices: [
    direct('ch01-choice-shield-jory-at-the-arrow', 'Shield Jory and the dispatch', 'You drag Jory behind the rear wheel and keep the tube in his hands.', [{ type: 'flag', operation: 'add', flagId: 'orchard-jory-shielded' }, { type: 'evidence', operation: 'add', evidenceId: 'route-seven-dispatch' }, { type: 'vitals', health: -2 }], 'ch01-living-split-fletched-arrow-battle', 'Meet the opening volley'),
    direct('ch01-choice-take-the-high-orchard-bank', 'Take the high bank', 'You climb above the wagon line and mark the disciplined shooter.', [{ type: 'flag', operation: 'add', flagId: 'orchard-high-bank-held' }, { type: 'vitals', resource: -2 }], 'ch01-living-split-fletched-arrow-battle', 'Meet the opening volley'),
    direct('ch01-choice-cut-the-damaged-wheel-loose', 'Cut the damaged wheel loose for cover', 'The wheel and sideboard drop into a low barricade.', [{ type: 'flag', operation: 'add', flagId: 'orchard-wheel-cover' }, { type: 'flag', operation: 'add', flagId: 'rear-wagon-disabled' }, { type: 'threat', amount: -1 }], 'ch01-living-split-fletched-arrow-battle', 'Meet the opening volley', { requirements: [{ type: 'flag', flagId: 'rear-wagon-braced-poorly' }], exclusions: [{ type: 'flag', flagId: 'replacement-fitting-installed' }] }),
    direct('ch01-choice-seize-the-lead-reins-at-arrow', 'Seize the lead reins', 'You turn the horses into the wall before they overturn the medicine wagon.', [{ type: 'flag', operation: 'add', flagId: 'orchard-horses-controlled' }, { type: 'flag', operation: 'add', flagId: 'lead-wagon-controlled' }, { type: 'vitals', health: -2 }], 'ch01-living-split-fletched-arrow-battle', 'Meet the opening volley'),
  ] }),
  base({ id: 'ch01-living-split-fletched-arrow-battle', slot: 18, type: 'journey', journeySubtype: 'travel', family: 'split-fletched-arrow-battle-setup', pacing: 'danger', illustrationId: 'scene-ch01-living-split-fletched-arrow-battle', title: 'The Opening Volley', line: 'Two fingers. The smoke used the same count.', narrative: ['A goblin cinder thrower rises behind the orchard wall while a human reaver moves under the wagon line.'], choices: [
    checked('ch01-choice-read-the-orchard-signal', 'Read the signal before it falls', 'cunning', 7, 'Halen gave the exact cadence +10', 'ch01-living-split-fletched-arrow-aftermath', 'See what survived', [{ type: 'flag', operation: 'add', flagId: 'orchard-volley-called' }, { type: 'flag', operation: 'add', flagId: 'combat-ch01-orchard-cover' }, { type: 'vitals', resource: 1 }], 'enc-ch01-orchard-volley', { requirements: [{ type: 'flag', flagId: 'orchard-signal-known' }] }),
    checked('ch01-choice-hold-the-wagon-barricade', 'Hold the wheel barricade', 'strength', 7, 'Dropped sideboard +5', 'ch01-living-split-fletched-arrow-aftermath', 'See what survived', [{ type: 'flag', operation: 'add', flagId: 'combat-ch01-orchard-cover' }, { type: 'flag', operation: 'add', flagId: 'medicine-protected-at-orchard' }], 'enc-ch01-orchard-volley', { requirements: [{ type: 'flag', flagId: 'orchard-wheel-cover' }] }),
    direct('ch01-choice-charge-from-the-high-bank', 'Charge the uphill shooter', 'You force the signal archer away from the prepared lane.', [{ type: 'flag', operation: 'add', flagId: 'combat-ch01-orchard-charge' }, { type: 'vitals', health: -2 }, { type: 'combat', encounterId: 'enc-ch01-orchard-volley' }], 'ch01-living-split-fletched-arrow-aftermath', 'Break the orchard line', { requirements: [{ type: 'flag', flagId: 'orchard-high-bank-held' }] }),
    direct('ch01-choice-form-around-jory-and-the-teams', 'Form around Jory and the teams', 'The guards close around the dispatch and horses as the reaver reaches the axle.', [{ type: 'flag', operation: 'add', flagId: 'combat-ch01-orchard-cover' }, { type: 'flag', operation: 'add', flagId: 'jory-and-teams-held' }, { type: 'combat', encounterId: 'enc-ch01-orchard-volley' }], 'ch01-living-split-fletched-arrow-aftermath', 'See what survived'),
  ] }),
  base({ id: 'ch01-living-split-fletched-arrow-aftermath', slot: 19, type: 'journey', journeySubtype: 'investigation', family: 'split-fletched-arrow-aftermath', pacing: 'recovery', illustrationId: 'scene-ch01-living-split-fletched-arrow-aftermath', title: 'The Arrow After Battle', line: 'Royal metal, altered on the road. That is evidence of a supply chain, not proof of a uniform.', narrative: ['The orchard falls quiet. Beneath the fresh feathers, the arrowhead bears a royal workshop notch.'], choices: [
    direct('ch01-choice-preserve-the-split-fletched-arrow', 'Preserve the complete arrow', 'Jory splints the shaft between two boards and keeps every material clue.', [{ type: 'evidence', operation: 'add', evidenceId: 'royal-arrow' }, { type: 'flag', operation: 'add', flagId: 'split-fletched-arrow-secured' }, { type: 'flag', operation: 'add', flagId: 'royal-arrow-intact' }, { type: 'xp', amount: 8, source: 'story' }], 'ch01-main-the-bridge-in-smoke', 'Carry the wounded toward the bridge'),
    direct('ch01-choice-take-the-marked-arrowhead', 'Take the marked head', 'You remove the stamped head and bag the replaced feathers separately.', [{ type: 'evidence', operation: 'add', evidenceId: 'royal-arrow' }, { type: 'flag', operation: 'add', flagId: 'split-fletched-arrow-secured' }, { type: 'flag', operation: 'add', flagId: 'royal-arrow-head-only' }, { type: 'threat', amount: -1 }], 'ch01-main-the-bridge-in-smoke', 'Move before the raiders regroup'),
    direct('ch01-choice-treat-the-orchard-wounded', 'Treat the wounded before moving', 'You spend the remaining light on pressure dressings while Jory secures the arrow.', [{ type: 'vitals', resource: -2 }, { type: 'flag', operation: 'add', flagId: 'orchard-wounded-stabilized' }, { type: 'evidence', operation: 'add', evidenceId: 'royal-arrow' }, { type: 'flag', operation: 'add', flagId: 'split-fletched-arrow-secured' }, { type: 'faction', factionId: 'greywatch', amount: 1 }, { type: 'tension', amount: 1 }], 'ch01-main-the-bridge-in-smoke', 'Take the bridge road'),
  ] }),
]);
