import { defineScene } from '../../builders';
const routes = ['kings-road', 'old-forest', 'ruined-pass'];
const base = (scene: any) => defineScene({ chapterId: 'ch01', region: 'gloamwood', weight: 100, eligibility: { routes, minLevel: 1, maxLevel: 2 }, requirements: [], exclusions: [], cooldownRuns: 0, oneShot: true, followUps: [], callbackPromises: [], dialogue: [{ speakerName: 'Jory', text: scene.line, environmentIllustrationId: scene.illustrationId }], ...scene });
const direct = (id: string, label: string, outcome: string, effects: any[], nextSceneId: string, continueLabel: string, extra = {}) => ({ id, label, detail: outcome, outcome, effects, nextSceneId, continueLabel, ...extra });
const checked = (id: string, label: string, stat: 'strength' | 'cunning' | 'will', difficulty: number, modifier: string, nextSceneId: string, continueLabel: string, effects: any[], combatEncounterId?: string, extra = {}) => ({ id, label, detail: `Attempt a ${stat} check.`, ...extra, check: { stat, difficulty, modifiers: [{ label: modifier, amount: 5 }], success: { outcome: 'You complete the work before the trap can answer.', effects, nextSceneId, continueLabel }, failure: { outcome: 'The road takes a cost but yields enough to continue.', effects, nextSceneId, continueLabel }, criticalSuccess: { outcome: 'You preserve a useful record as well as the convoy.', effects, nextSceneId, continueLabel }, criticalFailure: { outcome: 'The hidden enemy uses the opening.', effects, nextSceneId, continueLabel, ...(combatEncounterId ? { combatEncounterId } : {}) } } });

export const CH01_LIVING_TOLLHOUSE = Object.freeze([
  base({ id: 'ch01-living-snared-scout-setup', slot: 12, type: 'journey', journeySubtype: 'side-quest', family: 'snared-scout', pacing: 'danger', illustrationId: 'scene-ch01-living-snared-scout-setup', title: 'A Boot Above the Bracken', line: 'Halen makes a warning sound through the gag and looks at the leaves below him.', narrative: ['Scout Halen Reeve hangs by one ankle from a bent ash sapling while a second wire lies slack below.'], choices: [
    direct('ch01-choice-stop-beyond-the-second-wire', 'Stop beyond the second wire', 'You halt the guards before anyone enters the trap.', [{ type: 'flag', operation: 'add', flagId: 'snare-second-wire-seen' }, { type: 'threat', amount: -1 }], 'ch01-living-snared-scout-choice', 'Free the scout'),
    direct('ch01-choice-order-the-wagons-forward-of-the-snare', 'Move the wagons past the exposed verge', 'The convoy rolls to a stone shoulder while you stay with Halen.', [{ type: 'flag', operation: 'add', flagId: 'snare-wagons-sheltered' }, { type: 'tension', amount: 1 }], 'ch01-living-snared-scout-choice', 'Free the scout'),
  ] }),
  base({ id: 'ch01-living-snared-scout-choice', slot: 13, type: 'journey', journeySubtype: 'side-quest', family: 'snared-scout', pacing: 'danger', illustrationId: 'scene-ch01-living-snared-scout-choice', title: 'The Bent Sapling', line: 'Two humans in patrol cloaks. One goblin runner. They wanted the toll road left open.', narrative: ['The main rope can be cut quickly, but Halen will fall across the lower wire.'], choices: [
    checked('ch01-choice-catch-and-lower-halen', 'Catch and lower him', 'strength', 6, 'Jory holds the canvas +5', 'ch01-living-snared-scout-aftermath', "Treat Halen's leg", [{ type: 'flag', operation: 'add', flagId: 'snared-scout-rescued' }, { type: 'xp', amount: 10, source: 'quest' }, { type: 'faction', factionId: 'greywatch', amount: 1 }]),
    checked('ch01-choice-keep-halen-talking', 'Free him while he gives the warning', 'will', 6, 'Halen is trained +5', 'ch01-living-snared-scout-aftermath', "Treat Halen's leg", [{ type: 'flag', operation: 'add', flagId: 'snared-scout-rescued' }, { type: 'evidence', operation: 'add', evidenceId: 'halen-orchard-warning' }, { type: 'xp', amount: 10, source: 'quest' }]),
    direct('ch01-choice-map-the-snare-before-cutting', 'Investigate the trap first', 'You trace the lower wire to a muffled bell before lowering Halen.', [{ type: 'flag', operation: 'add', flagId: 'snared-scout-rescued' }, { type: 'flag', operation: 'add', flagId: 'tollhouse-bell-pattern-known' }, { type: 'xp', amount: 8, source: 'quest' }, { type: 'tension', amount: 1 }], 'ch01-living-snared-scout-aftermath', "Treat Halen's leg", { requirements: [{ type: 'flag', flagId: 'snare-second-wire-seen' }] }),
  ] }),
  base({ id: 'ch01-living-snared-scout-aftermath', slot: 14, type: 'journey', journeySubtype: 'side-quest', family: 'snared-scout-aftermath', pacing: 'recovery', illustrationId: 'scene-ch01-living-snared-scout-aftermath', title: "Halen's Choice of Shelter", line: 'Take me if you need a witness. Leave the whistle if you need the hour.', narrative: ['Halen can ride with the medicine or remain hidden at a scout cache until his leg wakes.'], choices: [
    direct('ch01-choice-carry-halen-with-the-convoy', 'Carry Halen to Greywatch', 'A bandage crate moves under oilcloth and Halen takes its place beside Jory.', [{ type: 'flag', operation: 'add', flagId: 'halen-with-convoy' }, { type: 'faction', factionId: 'greywatch', amount: 1 }, { type: 'tension', amount: 1 }], 'ch01-living-smoke-verge-setup', "Follow Halen's warning"),
    direct('ch01-choice-hide-halen-at-the-scout-cache', 'Hide Halen at the scout cache', 'You leave water, a bandage, and his brass whistle within reach.', [{ type: 'flag', operation: 'add', flagId: 'halen-hidden-alive' }, { type: 'item', operation: 'grant', itemId: 'tool-signal-whistle', quantity: 1, destination: 'pack' }, { type: 'threat', amount: -1 }], 'ch01-living-smoke-verge-setup', 'Watch the northern smoke'),
  ] }),
  base({ id: 'ch01-living-bell-wire-setup', slot: 12, type: 'journey', journeySubtype: 'investigation', family: 'bell-wire', pacing: 'danger', illustrationId: 'scene-ch01-living-bell-wire-setup', title: 'Wire Under the Desk', line: 'The register was not torn free. Its chain was made into a trigger.', narrative: ['A polished wire passes through the toll desk floorboard to a muffled bell beneath the orchard eaves.'], choices: [
    direct('ch01-choice-clear-the-tollhouse-doorway', 'Clear the doorway', 'Jory moves everyone beyond the wire before you touch it.', [{ type: 'flag', operation: 'add', flagId: 'bell-wire-doorway-cleared' }, { type: 'tension', amount: 1 }], 'ch01-living-bell-wire-choice', 'Trace the bell wire'),
    direct('ch01-choice-hold-the-wire-still', 'Pin the wire', 'A knife through the floor gap keeps the wire still.', [{ type: 'vitals', resource: -1 }, { type: 'flag', operation: 'add', flagId: 'bell-wire-pinned' }], 'ch01-living-bell-wire-choice', 'Trace the bell wire'),
  ] }),
  base({ id: 'ch01-living-bell-wire-choice', slot: 13, type: 'journey', journeySubtype: 'investigation', family: 'bell-wire', pacing: 'danger', illustrationId: 'scene-ch01-living-bell-wire-choice', title: 'The Muffled Bell', line: 'Bell or cellar. Whoever built this wanted us looking the wrong way.', narrative: ['A second branch of wire drops toward the cellar latch, making a careless disarm open both threats.'], choices: [
    checked('ch01-choice-disarm-the-bell-wire', 'Disarm both branches', 'cunning', 7, 'Wire pinned +5', 'ch01-living-bell-wire-aftermath', 'Move the toll desk', [{ type: 'flag', operation: 'add', flagId: 'bell-wire-disarmed' }, { type: 'xp', amount: 10, source: 'story' }], 'enc-ch01-tollhouse-lookouts'),
    checked('ch01-choice-rip-the-bell-from-the-wall', 'Break the bell loose', 'strength', 7, 'Rotten wall boards +5', 'ch01-living-bell-wire-aftermath', 'Move the toll desk', [{ type: 'flag', operation: 'add', flagId: 'bell-wire-broken-silent' }, { type: 'xp', amount: 10, source: 'story' }], 'enc-ch01-tollhouse-lookouts'),
    checked('ch01-choice-lure-the-bell-watcher', "Ring the watcher's answer", 'will', 7, 'Escape line already known +5', 'ch01-living-bell-wire-aftermath', 'Move the toll desk', [{ type: 'flag', operation: 'add', flagId: 'tollhouse-watcher-captured' }, { type: 'evidence', operation: 'add', evidenceId: 'watcher-patrol-cloak' }, { type: 'xp', amount: 10, source: 'quest' }], 'enc-ch01-tollhouse-lookouts'),
  ] }),
  base({ id: 'ch01-living-bell-wire-aftermath', slot: 14, type: 'journey', journeySubtype: 'investigation', family: 'bell-wire-aftermath', pacing: 'recovery', illustrationId: 'scene-ch01-living-bell-wire-aftermath', title: 'What the Alarm Guarded', line: 'Then you can explain the missing register below it.', narrative: ['A square trapdoor lies beneath the moved desk, keyed to the cellar latch and marked by military boot scrapes.'], choices: [
    direct('ch01-choice-open-the-cellar-after-the-bell', 'Open the cellar', 'Jory fits the tollhouse key while guards stand clear.', [{ type: 'flag', operation: 'add', flagId: 'cellar-entered-after-alarm' }, { type: 'xp', amount: 8, source: 'story' }], 'ch01-living-below-desk-setup', 'Descend below the toll desk'),
    direct('ch01-choice-secure-the-yard-before-cellar', 'Secure the yard first', 'The wagons form behind the barrier before the trapdoor opens.', [{ type: 'flag', operation: 'add', flagId: 'tollhouse-yard-secured' }, { type: 'threat', amount: -1 }, { type: 'tension', amount: 1 }], 'ch01-living-below-desk-setup', 'Open the trapdoor'),
  ] }),
  base({ id: 'ch01-living-below-desk-setup', slot: 14, type: 'journey', journeySubtype: 'dungeon', family: 'below-toll-desk', pacing: 'danger', illustrationId: 'scene-ch01-living-below-desk-setup', title: 'The Square Trapdoor', line: 'The register is in reach. The strongbox is not.', narrative: ['The first cellar stair has been sawn almost through above uniform crates, a strongbox, and torn register pages.'], choices: [
    direct('ch01-choice-bridge-the-sawn-step', 'Bridge the sawn step', 'A door plank spans the cut stair and gives the descent one safe line.', [{ type: 'flag', operation: 'add', flagId: 'cellar-step-bridged' }, { type: 'vitals', resource: -1 }], 'ch01-living-below-desk-choice', 'Enter the cellar'),
    direct('ch01-choice-lower-a-lamp-before-entering', 'Lower a lamp first', 'The lamp reveals a trip cord between the register and strongbox.', [{ type: 'flag', operation: 'add', flagId: 'cellar-tripcord-seen' }, { type: 'vitals', resource: -1 }], 'ch01-living-below-desk-choice', 'Enter the cellar'),
  ] }),
  base({ id: 'ch01-living-below-desk-choice', slot: 15, type: 'journey', journeySubtype: 'dungeon', family: 'below-toll-desk', pacing: 'danger', illustrationId: 'scene-ch01-living-below-desk-choice', title: 'Register, Strongbox, Tunnel', line: 'Leave the book and climb out.', narrative: ['The register records empty military carts, the strongbox is wired to a weight, and a low tunnel reaches the orchard.'], choices: [
    checked('ch01-choice-preserve-the-cellar-register', 'Preserve the register and badge cuts', 'cunning', 7, 'Jory knows record handling +5', 'ch01-living-below-desk-aftermath', 'Account for the evidence', [{ type: 'evidence', operation: 'add', evidenceId: 'tollhouse-register-page' }, { type: 'flag', operation: 'add', flagId: 'removed-greywatch-badges-recorded' }, { type: 'xp', amount: 10, source: 'story' }]),
    checked('ch01-choice-lift-the-cellar-weight', 'Lift the trap weight off the strongbox', 'strength', 7, 'Trip cord visible +5', 'ch01-living-below-desk-aftermath', 'Account for the evidence', [{ type: 'flag', operation: 'add', flagId: 'tollhouse-cache-opened' }, { type: 'gold', scope: 'unbanked', amount: 6 }, { type: 'item', operation: 'grant', itemId: 'charm-greywatch-key', quantity: 1, destination: 'unbanked-loot' }, { type: 'xp', amount: 10, source: 'quest' }], 'enc-ch01-tollhouse-cellar'),
    direct('ch01-choice-enter-the-cellar-tunnel', 'Block the tunnel before searching', 'You move into the low passage before its occupants can reach the stair.', [{ type: 'flag', operation: 'add', flagId: 'cellar-raiders-engaged' }, { type: 'combat', encounterId: 'enc-ch01-tollhouse-cellar' }], 'ch01-living-below-desk-aftermath', 'Clear the hidden tunnel'),
  ] }),
  base({ id: 'ch01-living-below-desk-aftermath', slot: 16, type: 'journey', journeySubtype: 'dungeon', family: 'below-toll-desk-aftermath', pacing: 'recovery', illustrationId: 'scene-ch01-living-below-desk-aftermath', title: 'The Missing Badges', line: 'This proves uniforms were taken. It does not prove who wore them.', narrative: ['Clean badge-shaped cuts in the uniform crates connect trained people to stolen Greywatch cloaks.'], choices: [
    direct('ch01-choice-seal-the-tollhouse-evidence', 'Seal the evidence with the dispatch', 'Jory wraps pages and alarm pieces in separate waxed cloths.', [{ type: 'flag', operation: 'add', flagId: 'tollhouse-evidence-sealed' }, { type: 'xp', amount: 8, source: 'story' }], 'ch01-living-smoke-verge-setup', 'Follow the fresh smoke'),
    direct('ch01-choice-collapse-the-cellar-tunnel', 'Close the orchard tunnel', 'The guards pull the sawn stair into the low passage and block it.', [{ type: 'flag', operation: 'add', flagId: 'tollhouse-tunnel-collapsed' }, { type: 'threat', amount: -2 }, { type: 'tension', amount: 1 }], 'ch01-living-smoke-verge-setup', 'Return to the convoy'),
  ] }),
]);
