import { defineScene } from '../../builders';

export const CH01_MAIN = Object.freeze([
  defineScene({
    id: 'ch01-main-three-days-to-greywatch',
    chapterId: 'ch01',
    region: 'gloamwood',
    slot: 1,
    type: 'main',
    family: 'caravan-departure',
    anchorOrder: 1,
    weight: 100,
    pacing: 'quiet',
    illustrationId: 'scene-ch01-main-three-days-to-greywatch',
    title: 'Three Days to Greywatch',
    narrative: [
      'Two medicine wagons leave Dunmere before sunrise, bound for Greywatch on the northern border. You are the hired guard, not an officer, and your pay depends on both wagons arriving.',
      'Junior stores clerk Jory Fen carries the Route Seven dispatch in a waxed leather tube. He asks whether you want one last inspection or an early lead on the road.',
    ],
    eligibility: { routes: ['kings-road', 'old-forest', 'ruined-pass'], minLevel: 1, maxLevel: 2 },
    requirements: [],
    exclusions: [],
    cooldownRuns: 0,
    oneShot: true,
    followUps: [],
    callbackPromises: [],
    choices: [
      {
        id: 'ch01-choice-inspect-the-wagons',
        label: 'Inspect the wagons',
        detail: 'Spend the cool morning checking wheels and seals, but surrender the caravan\'s early start.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'medicine-wagons-inspected' },
          { type: 'tension', amount: -1 },
        ],
        outcome: 'You tighten a loose axle pin and record every crate before the drivers take the north road.',
      },
      {
        id: 'ch01-choice-leave-before-traffic',
        label: 'Leave before traffic',
        detail: 'Gain distance before the toll queues form, but accept the risk of an unchecked wagon fault.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'caravan-left-early' },
          { type: 'threat', amount: -1 },
        ],
        outcome: 'The wagons clear Dunmere while its gates are still opening, with every crate still under its canvas.',
      },
    ],
  }),
  defineScene({
    id: 'ch01-main-medicine-for-the-north',
    chapterId: 'ch01',
    region: 'gloamwood',
    slot: 6,
    type: 'main',
    family: 'medicine-convoy',
    anchorOrder: 2,
    weight: 100,
    pacing: 'quiet',
    illustrationId: 'scene-ch01-main-medicine-for-the-north',
    title: 'Medicine for the North',
    narrative: [
      'At the first steep grade, Jory opens the manifest: fever bark, wound spirits, clean bandages, and six locked cases for Greywatch\'s infirmary. The rear wagon is already riding low on one spring.',
      'The road ahead is firm, but rain is building over the hills. The convoy can protect the cargo or protect its speed, not both.',
    ],
    eligibility: { routes: ['kings-road', 'old-forest', 'ruined-pass'], minLevel: 1, maxLevel: 2 },
    requirements: [],
    exclusions: [],
    cooldownRuns: 0,
    oneShot: true,
    followUps: [],
    callbackPromises: [],
    choices: [
      {
        id: 'ch01-choice-brace-the-medicine-cases',
        label: 'Brace the medicine cases',
        detail: 'Use spare boards to protect the locked cases, but make later wheel repairs harder.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'medicine-secured' },
          { type: 'flag', operation: 'add', flagId: 'repair-timber-spent' },
        ],
        outcome: 'The drivers lash each case against the wagon frame until nothing shifts on the climb.',
      },
      {
        id: 'ch01-choice-lighten-the-rear-wagon',
        label: 'Lighten the rear wagon',
        detail: 'Move heavy crates between wagons and lose an hour, reducing the risk of a broken spring.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'wagon-load-balanced' },
          { type: 'tension', amount: 1 },
        ],
        outcome: 'The rear wagon rises on its spring, and the convoy resumes with dusk one hour closer.',
      },
    ],
  }),
  defineScene({
    id: 'ch01-main-the-empty-tollhouse',
    chapterId: 'ch01',
    region: 'gloamwood',
    slot: 11,
    type: 'main',
    family: 'abandoned-checkpoint',
    anchorOrder: 3,
    weight: 100,
    pacing: 'quiet',
    illustrationId: 'scene-ch01-main-the-empty-tollhouse',
    title: 'The Empty Tollhouse',
    narrative: [
      'Route Seven reaches an official tollhouse at midday. Its barrier is raised, the stove is cold, and no collector answers Jory\'s call.',
      'A half-eaten meal sits inside beside a register torn cleanly from its chain. The road dust carries fresh boot marks toward the orchard north of the post.',
    ],
    eligibility: { routes: ['kings-road', 'old-forest', 'ruined-pass'], minLevel: 1, maxLevel: 2 },
    requirements: [],
    exclusions: [],
    cooldownRuns: 0,
    oneShot: true,
    followUps: [],
    callbackPromises: [],
    choices: [
      {
        id: 'ch01-choice-search-the-tollhouse',
        label: 'Search the tollhouse',
        detail: 'Delay the convoy in an exposed position to look for the missing collector and register.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'tollhouse-searched' },
          { type: 'threat', amount: 1 },
        ],
        outcome: 'You find a fresh military boot scrape beneath the desk and a key to the locked cellar.',
      },
      {
        id: 'ch01-choice-push-the-wagons-through',
        label: 'Push the wagons through',
        detail: 'Keep the medicine moving, but leave the missing officials and their records unresolved.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'tollhouse-bypassed' },
          { type: 'threat', amount: -1 },
        ],
        outcome: 'The wagons cross the raised barrier while Jory marks the abandoned post in his own ledger.',
      },
    ],
  }),
  defineScene({
    id: 'ch01-main-the-first-arrow',
    chapterId: 'ch01',
    region: 'gloamwood',
    slot: 17,
    type: 'main',
    family: 'first-ambush',
    anchorOrder: 4,
    weight: 100,
    pacing: 'danger',
    threatChange: 2,
    illustrationId: 'scene-ch01-main-the-first-arrow',
    title: 'The First Arrow',
    narrative: [
      'The first arrow kills the lead driver before anyone hears a bowstring. The second punches through Jory\'s satchel and pins the leather dispatch tube against the wagon rail.',
      'Its black-and-white fletching belongs to a royal armory pattern that border raiders should not possess. Shapes move between the orchard rows as the horses begin to bolt.',
    ],
    eligibility: { routes: ['kings-road', 'old-forest', 'ruined-pass'], minLevel: 1, maxLevel: 2 },
    requirements: [],
    exclusions: [],
    cooldownRuns: 0,
    oneShot: true,
    followUps: [],
    callbackPromises: [],
    choices: [
      {
        id: 'ch01-choice-cover-jory-and-the-dispatch',
        label: 'Cover Jory and the dispatch',
        detail: 'Hold beside the clerk under direct fire, but leave the frightened horses to the drivers.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'jory-shielded' },
          { type: 'evidence', operation: 'add', evidenceId: 'route-seven-dispatch' },
        ],
        outcome: 'You drag Jory and the pierced tube behind the rear wheel as more arrows strike the wagon.',
      },
      {
        id: 'ch01-choice-seize-the-lead-reins',
        label: 'Seize the lead reins',
        detail: 'Save the medicine wagon from overturning, but risk leaving Jory exposed for several breaths.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'lead-wagon-controlled' },
          { type: 'threat', amount: 1 },
        ],
        outcome: 'You turn the horses into the ditch before they can drag the wagon through the killing ground.',
      },
    ],
  }),
  defineScene({
    id: 'ch01-main-the-bridge-in-smoke',
    chapterId: 'ch01',
    region: 'gloamwood',
    slot: 24,
    type: 'main',
    family: 'bridge-rescue',
    anchorOrder: 5,
    weight: 100,
    pacing: 'danger',
    threatChange: 2,
    illustrationId: 'scene-ch01-main-the-bridge-in-smoke',
    title: 'The Bridge in Smoke',
    narrative: [
      'The surviving raiders fire the timber bridge and drive a cart of villagers against the blocked approach. One wounded toll officer lies beneath the cart, still holding a Greywatch duty badge.',
      'The medicine wagon can cross only after someone clears the span. Border scout Mara Vey is already cutting civilians free while arrows strike the railing.',
    ],
    eligibility: { routes: ['kings-road', 'old-forest', 'ruined-pass'], minLevel: 1, maxLevel: 2 },
    requirements: [],
    exclusions: [],
    cooldownRuns: 0,
    oneShot: true,
    followUps: ['ch01-companion-mara-at-the-burning-bridge'],
    callbackPromises: [],
    choices: [
      {
        id: 'ch01-choice-clear-a-path-for-civilians',
        label: 'Clear a path for civilians',
        detail: 'Fight beside Mara to free the trapped families, while the medicine remains exposed to fire.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'greywatch-civilians-protected' },
          { type: 'companion-loyalty', companionId: 'mara', amount: 8 },
        ],
        outcome: 'The villagers reach the far bank with the wounded officer, but sparks settle across the wagon canvas.',
      },
      {
        id: 'ch01-choice-drag-the-medicine-through',
        label: 'Drag the medicine through',
        detail: 'Save the locked cases before the bridge fails, but leave Mara with fewer hands for the rescue.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'medicine-prioritized-at-bridge' },
          { type: 'companion-loyalty', companionId: 'mara', amount: -5 },
        ],
        outcome: 'The medicine crosses intact while Mara and two villagers pull the last trapped family from the cart.',
      },
    ],
  }),
  defineScene({
    id: 'ch01-main-a-banner-placed-too-neatly',
    chapterId: 'ch01',
    region: 'gloamwood',
    slot: 32,
    type: 'main',
    family: 'false-evidence',
    anchorOrder: 6,
    weight: 100,
    pacing: 'quiet',
    illustrationId: 'scene-ch01-main-a-banner-placed-too-neatly',
    title: 'A Banner Placed Too Neatly',
    narrative: [
      'Beyond the bridge, searchers find the missing toll collector dead beside a clean orc war banner. He is not the wounded officer rescued from the cart. The cloth is dry despite the wet ditch, and its pole has never been planted in soil.',
      'Jory finds a royal-armory arrow beneath the body. You notice that the collector\'s boots were removed and put back on after death.',
    ],
    eligibility: { routes: ['kings-road', 'old-forest', 'ruined-pass'], minLevel: 1, maxLevel: 2 },
    requirements: [],
    exclusions: [],
    cooldownRuns: 0,
    oneShot: true,
    followUps: [],
    callbackPromises: [],
    choices: [
      {
        id: 'ch01-choice-record-the-scene-before-moving-it',
        label: 'Record the scene before moving it',
        detail: 'Spend daylight measuring tracks and cloth position, but give any pursuers time to close.',
        effects: [
          { type: 'evidence', operation: 'add', evidenceId: 'royal-arrow' },
          { type: 'flag', operation: 'add', flagId: 'false-banner-documented' },
          { type: 'threat', amount: 1 },
        ],
        outcome: 'Jory sketches the body, arrow, and untouched soil before wrapping the evidence in clean canvas.',
      },
      {
        id: 'ch01-choice-take-the-banner-and-move',
        label: 'Take the banner and move',
        detail: 'Carry the obvious clue to Greywatch quickly, but lose details that could prove it was staged.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'orc-banner-recovered' },
          { type: 'threat', amount: -1 },
        ],
        outcome: 'Mara rolls the dry banner around its unused pole, and the caravan leaves the ditch behind.',
      },
    ],
  }),
  defineScene({
    id: 'ch01-main-before-the-gates-close',
    chapterId: 'ch01',
    region: 'gloamwood',
    slot: 41,
    type: 'main',
    family: 'greywatch-arrival',
    anchorOrder: 7,
    weight: 100,
    pacing: 'danger',
    illustrationId: 'scene-ch01-main-before-the-gates-close',
    title: 'Before the Gates Close',
    narrative: [
      'Greywatch closes its outer gate while the damaged wagons climb the final hill. Archers shout that raiders have been seen east of the wall and refuse entry without proof of official business.',
      'Jory can present the Route Seven dispatch, but doing so reveals exactly what the caravan carries. The wounded toll officer and the staged banner make a quieter entry possible among the refugees.',
    ],
    eligibility: { routes: ['kings-road', 'old-forest', 'ruined-pass'], minLevel: 1, maxLevel: 2 },
    requirements: [],
    exclusions: [],
    cooldownRuns: 0,
    oneShot: true,
    followUps: ['ch02-main-warning-before-dawn'],
    callbackPromises: [],
    choices: [
      {
        id: 'ch01-choice-present-the-route-seven-dispatch',
        label: 'Present the Route Seven dispatch',
        detail: 'Prove the convoy\'s authority at the gate, but let every watching soldier see the sealed tube.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'dispatch-presented-at-gate' },
          { type: 'faction', factionId: 'greywatch', amount: 2 },
        ],
        outcome: 'The gate captain reads the route code and brings the wagons inside under an armed escort.',
      },
      {
        id: 'ch01-choice-enter-with-the-refugees',
        label: 'Enter with the refugees',
        detail: 'Hide the evidence from the gate crowd, but delay the medicine while guards inspect every cart.',
        effects: [
          { type: 'flag', operation: 'add', flagId: 'evidence-entered-greywatch-quietly' },
          { type: 'tension', amount: 1 },
        ],
        outcome: 'You place the wounded officer where the sentries can see him, and the convoy passes without naming its proof.',
      },
    ],
  }),
]);
